/*
* generated by Xtext
*/
package org.best.of.robotics;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SmachDSLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.best.of.robotics.ui.internal.SmachDSLActivator.getInstance().getInjector("org.best.of.robotics.SmachDSL");
	}
	
}
