/*
 * generated by Xtext
 */
package org.best.of.robotics.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmachDSLUiModule extends org.best.of.robotics.ui.AbstractSmachDSLUiModule {
	public SmachDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
