/*
 * generated by Xtext
 */
package org.ros.model;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ROS_PackageRuntimeModule extends org.ros.model.AbstractROS_PackageRuntimeModule {

}
