/*
 * generated by Xtext
 */
package org.best.of.robotics;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmachDSLRuntimeModule extends org.best.of.robotics.AbstractSmachDSLRuntimeModule {

}
