/*
* generated by Xtext
*/
package org.best.of.robotics.ui.contentassist;

import org.best.of.robotics.ui.contentassist.AbstractSmachDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SmachDSLProposalProvider extends AbstractSmachDSLProposalProvider {

}
