Orocos Real-Time Toolkit: RTT::base::ChannelElementBase Class Reference
RTT::base::ChannelElementBase Class Reference
In the data flow implementation, a channel is created by chaining ChannelElementBase objects.
#include <rtt/base/ChannelElementBase.hpp>
Public Types
typedef boost::intrusive_ptr
< ChannelElementBase > shared_ptr
Public Member Functions
ChannelElementBase ()
A default constructed ChannelElementBase has no input nor output configured.
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInput ()
Returns the current input channel element.
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool inputReady ()
This is called by an input port when it is ready to receive data.
virtual void clear ()
Clears any data stored by the channel.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Friends
void RTT_API intrusive_ptr_add_ref (ChannelElementBase *e)
void RTT_API intrusive_ptr_release (ChannelElementBase *e)
Detailed Description
In the data flow implementation, a channel is created by chaining ChannelElementBase objects.
ChannelElementBase objects are refcounted. In the chain, an element maintains the refcount for its successor, and holds a simple pointer to its predecessor.
Definition at line 59 of file ChannelElementBase.hpp.
Constructor & Destructor Documentation
ChannelElementBase::ChannelElementBase ()
A default constructed ChannelElementBase has no input nor output configured.
The only way to set an input or output is to use setOutput().
Definition at line 46 of file ChannelInterface.cpp.
References ORO_ATOMIC_SETUP().
Member Function Documentation
virtual void RTT::base::ChannelElementBase::clear () [virtual]
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
virtual void RTT::base::ChannelElementBase::disconnect (bool forward) [virtual]
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::corba::RemoteChannelElement< T >.
ChannelElementBase::shared_ptr ChannelElementBase::getInput ()
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to setOutput().
Returns:
Reimplemented in RTT::base::ChannelElement< T >.
Definition at line 58 of file ChannelInterface.cpp.
Referenced by getInputEndPoint().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint ()
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns:
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 96 of file ChannelInterface.cpp.
References getInput().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint ()
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns:
getOutput() ? getOutput()->getInputEndPoint() : this
Definition at line 101 of file ChannelInterface.cpp.
References getOutput().
virtual PortInterface* RTT::base::ChannelElementBase::getPort () const [virtual]
Gets the port this channel element is connected to.
Returns:
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, and RTT::internal::ConnOutputEndpoint< T >.
virtual bool RTT::base::ChannelElementBase::inputReady () [virtual]
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns:
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
void RTT::base::ChannelElementBase::removeInput ()
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters:
output the next element in chain.
Definition at line 68 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), and RTT::internal::ConnFactory::buildChannelInput().
virtual bool RTT::base::ChannelElementBase::signal () [virtual]
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns:
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Referenced by RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
The documentation for this class was generated from the following files:
rtt/base/ChannelElementBase.hpp
rtt/base/ChannelInterface.cpp