Orocos Real-Time Toolkit: RTT::base::ActionInterface Class Reference
RTT::base::ActionInterface Class Reference
Based on the software pattern 'command', this interface allows execution of action objects.
#include <rtt/base/ActionInterface.hpp>
Public Types
typedef boost::shared_ptr
< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
virtual bool execute ()=0
Execute the functionality of this action.
virtual void reset ()
Reset this action.
virtual bool valid () const
Inspect if this action was executed and valid.
virtual void readArguments ()=0
This is invoked some time before execute() at a time when the action may read its function arguments.
virtual ActionInterface * clone () const =0
The Clone Software Pattern.
virtual ActionInterface * copy (std::map< const DataSourceBase *, DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
Based on the software pattern 'command', this interface allows execution of action objects.
The action may return true or false to indicate if it was accepted (true) or rejected (false).
Copy versus clone semantics
Copy is used to copy a whole tree of actions,
storing common information in web of internal::DataSource's. The internal::DataSource 'web' will be copied such that an entirely new action tree references the new DataSources.
When clone is used, the Datasources remain
in place, and only the action is cloned, thus, the original and the clone point to the same DataSource. The deletion of DataSources must thus be managed with smart pointers. A clone is thus used for within the existing internal::DataSource web.
Definition at line 71 of file ActionInterface.hpp.
Member Function Documentation
ActionInterface * RTT::ActionInterface::copy (std::map< const DataSourceBase *, DataSourceBase * > & alreadyCloned) const [virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::internal::AssignCommand< T, S >, RTT::scripting::CallFunction, RTT::scripting::CommandComposite, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 60 of file ActionInterface.cpp.
References clone().
Referenced by RTT::scripting::TryCommand::copy(), RTT::internal::ActionAliasAssignableDataSource< T >::copy(), RTT::internal::ActionAliasDataSource< T >::copy(), and RTT::internal::DataSourceCommand::copy().
virtual bool RTT::base::ActionInterface::execute () [pure virtual]
Execute the functionality of this action.
Returns:
true if the action was accepted, false otherwise
Implemented in RTT::internal::AssignCommand< T, S >, RTT::scripting::CallFunction, RTT::scripting::CommandComposite, RTT::scripting::CommandCounter, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::CommandFunction, RTT::scripting::CommandIllegal, RTT::scripting::CommandNOP, RTT::scripting::CommandString, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Referenced by RTT::scripting::StateMachine::activate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::scripting::VertexNode::execute(), RTT::scripting::TryCommand::execute(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::internal::DataSourceCommand::get(), RTT::internal::FusedMSignal< Signature >::invoke(), and RTT::scripting::Parser::parseValueStatement().
void RTT::ActionInterface::reset () [virtual]
Reset this action.
Must be used after execute() failed.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandCounter, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 50 of file ActionInterface.cpp.
Referenced by RTT::scripting::StateMachine::activate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::scripting::TryCommand::reset(), RTT::internal::DataSourceCommand::reset(), and RTT::scripting::VertexNode::startExecution().
bool RTT::ActionInterface::valid () const [virtual]
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandComposite, and RTT::scripting::TryCommand.
Definition at line 53 of file ActionInterface.cpp.
Referenced by RTT::scripting::VertexNode::isValid(), and RTT::scripting::TryCommand::valid().
The documentation for this class was generated from the following files:
rtt/base/ActionInterface.hpp
rtt/base/ActionInterface.cpp