Orocos Real-Time Toolkit: RTT::marsh::TiXmlUnknown Class Reference
RTT::marsh::TiXmlUnknown Class Reference
Any tag that tinyXml doesn't recognize is saved as an unknown.
#include <rtt/marsh/tinyxml.h>
Public Types
enum NodeType {
DOCUMENT, ELEMENT, COMMENT, UNKNOWN,
TEXT, DECLARATION, TYPECOUNT
}
The types of XML nodes supported by TinyXml.
enum {
TIXML_NO_ERROR = 0, TIXML_ERROR, TIXML_ERROR_OPENING_FILE, TIXML_ERROR_OUT_OF_MEMORY,
TIXML_ERROR_PARSING_ELEMENT, TIXML_ERROR_FAILED_TO_READ_ELEMENT_NAME, TIXML_ERROR_READING_ELEMENT_VALUE, TIXML_ERROR_READING_ATTRIBUTES,
TIXML_ERROR_PARSING_EMPTY, TIXML_ERROR_READING_END_TAG, TIXML_ERROR_PARSING_UNKNOWN, TIXML_ERROR_PARSING_COMMENT,
TIXML_ERROR_PARSING_DECLARATION, TIXML_ERROR_DOCUMENT_EMPTY, TIXML_ERROR_EMBEDDED_NULL, TIXML_ERROR_PARSING_CDATA,
TIXML_ERROR_STRING_COUNT
}
Public Member Functions
TiXmlUnknown (const TiXmlUnknown &copy)
void operator= (const TiXmlUnknown &copy)
virtual TiXmlNode * Clone () const
Creates a copy of this Unknown and returns it.
virtual void Print (FILE *cfile, int depth) const
Print this Unknown to a FILE stream.
virtual const char * Parse (const char *p, TiXmlParsingData *data, TiXmlEncoding encoding)
virtual const TiXmlUnknown * ToUnknown () const
Cast to a more defined type. Will return null not of the requested type.
virtual TiXmlUnknown * ToUnknown ()
Cast to a more defined type. Will return null not of the requested type.
const char * Value () const
The meaning of 'value' changes for the specific type of TiXmlNode.
void SetValue (const char *_value)
Changes the value of the node.
void Clear ()
Delete all the children of this node. Does not affect 'this'.
TiXmlNode * Parent ()
One step up the DOM.
const TiXmlNode * Parent () const
const TiXmlNode * FirstChild () const
The first child of this node. Will be null if there are no children.
TiXmlNode * FirstChild ()
const TiXmlNode * FirstChild (const char *value) const
The first child of this node with the matching 'value'. Will be null if none found.
TiXmlNode * FirstChild (const char *value)
The first child of this node with the matching 'value'. Will be null if none found.
const TiXmlNode * LastChild () const
TiXmlNode * LastChild ()
The last child of this node. Will be null if there are no children.
const TiXmlNode * LastChild (const char *value) const
TiXmlNode * LastChild (const char *value)
The last child of this node matching 'value'. Will be null if there are no children.
const TiXmlNode * IterateChildren (const TiXmlNode *previous) const
An alternate way to walk the children of a node.
TiXmlNode * IterateChildren (TiXmlNode *previous)
const TiXmlNode * IterateChildren (const char *value, const TiXmlNode *previous) const
This flavor of IterateChildren searches for children with a particular 'value'.
TiXmlNode * IterateChildren (const char *value, TiXmlNode *previous)
TiXmlNode * InsertEndChild (const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * LinkEndChild (TiXmlNode *addThis)
Add a new node related to this.
TiXmlNode * InsertBeforeChild (TiXmlNode *beforeThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * InsertAfterChild (TiXmlNode *afterThis, const TiXmlNode &addThis)
Add a new node related to this.
TiXmlNode * ReplaceChild (TiXmlNode *replaceThis, const TiXmlNode &withThis)
Replace a child of this node.
bool RemoveChild (TiXmlNode *removeThis)
Delete a child of this node.
const TiXmlNode * PreviousSibling () const
Navigate to a sibling node.
TiXmlNode * PreviousSibling ()
const TiXmlNode * PreviousSibling (const char *) const
Navigate to a sibling node.
TiXmlNode * PreviousSibling (const char *)
const TiXmlNode * NextSibling () const
Navigate to a sibling node.
TiXmlNode * NextSibling ()
const TiXmlNode * NextSibling (const char *) const
Navigate to a sibling node with the given 'value'.
TiXmlNode * NextSibling (const char *)
const TiXmlElement * NextSiblingElement () const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement ()
const TiXmlElement * NextSiblingElement (const char *) const
Convenience function to get through elements.
TiXmlElement * NextSiblingElement (const char *)
const TiXmlElement * FirstChildElement () const
Convenience function to get through elements.
TiXmlElement * FirstChildElement ()
const TiXmlElement * FirstChildElement (const char *value) const
Convenience function to get through elements.
TiXmlElement * FirstChildElement (const char *value)
int Type () const
Query the type (as an enumerated value, above) of this node.
const TiXmlDocument * GetDocument () const
Return a pointer to the Document this node lives in.
TiXmlDocument * GetDocument ()
bool NoChildren () const
Returns true if this node has no children.
virtual const TiXmlDocument * ToDocument () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDocument * ToDocument ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlElement * ToElement () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlElement * ToElement ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlComment * ToComment () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlComment * ToComment ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlText * ToText () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlText * ToText ()
Cast to a more defined type. Will return null if not of the requested type.
virtual const TiXmlDeclaration * ToDeclaration () const
Cast to a more defined type. Will return null if not of the requested type.
virtual TiXmlDeclaration * ToDeclaration ()
Cast to a more defined type. Will return null if not of the requested type.
int Row () const
Return the position, in the original source file, of this node or attribute.
int Column () const
See Row()
void SetUserData (void *user)
void * GetUserData ()
Static Public Member Functions
static void SetCondenseWhiteSpace (bool condense)
The world does not agree on whether white space should be kept or not.
static bool IsWhiteSpaceCondensed ()
Return the current white space setting.
Static Public Attributes
static const int utf8ByteTable [256]
Protected Member Functions
void CopyTo (TiXmlUnknown *target) const
virtual void StreamOut (TIXML_OSTREAM *out) const
void CopyTo (TiXmlNode *target) const
TiXmlNode * Identify (const char *start, TiXmlEncoding encoding)
Static Protected Member Functions
static const char * SkipWhiteSpace (const char *, TiXmlEncoding encoding)
static bool IsWhiteSpace (char c)
static bool IsWhiteSpace (int c)
static const char * ReadName (const char *p, TIXML_STRING *name, TiXmlEncoding encoding)
static const char * ReadText (const char *in, TIXML_STRING *text, bool ignoreWhiteSpace, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static const char * GetEntity (const char *in, char *value, int *length, TiXmlEncoding encoding)
static const char * GetChar (const char *p, char *_value, int *length, TiXmlEncoding encoding)
static void PutString (const TIXML_STRING &str, TIXML_OSTREAM *out)
static void PutString (const TIXML_STRING &str, TIXML_STRING *out)
static bool StringEqual (const char *p, const char *endTag, bool ignoreCase, TiXmlEncoding encoding)
static int IsAlpha (unsigned char anyByte, TiXmlEncoding encoding)
static int IsAlphaNum (unsigned char anyByte, TiXmlEncoding encoding)
static int ToLower (int v, TiXmlEncoding encoding)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
Protected Attributes
TiXmlNode * parent
NodeType type
TiXmlNode * firstChild
TiXmlNode * lastChild
TIXML_STRING value
TiXmlNode * prev
TiXmlNode * next
TiXmlCursor location
void * userData
Field containing a generic user pointer.
Static Protected Attributes
static const char * errorString [TIXML_ERROR_STRING_COUNT]
Friends
TIXML_OSTREAM & operator<< (TIXML_OSTREAM &out, const TiXmlNode &base)
Detailed Description
Any tag that tinyXml doesn't recognize is saved as an unknown.
It is a tag of text, but should not be modified. It will be written back to the XML, unchanged, when the file is saved.
DTD tags get thrown into TiXmlUnknowns.
Definition at line 1223 of file tinyxml.h.
Member Enumeration Documentation
enum RTT::marsh::TiXmlNode::NodeType [inherited]
The types of XML nodes supported by TinyXml.
(All the unsupported types are picked up by UNKNOWN.)
Definition at line 467 of file tinyxml.h.
Member Function Documentation
const TiXmlDocument * RTT::marsh::TiXmlNode::GetDocument () const [inherited]
Return a pointer to the Document this node lives in.
Returns null if not in a document.
Definition at line 631 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::ToDocument().
Referenced by RTT::marsh::TiXmlNode::LinkEndChild(), and RTT::marsh::TiXmlElement::SetAttribute().
TiXmlNode * RTT::marsh::TiXmlNode::InsertAfterChild (TiXmlNode * afterThis, const TiXmlNode & addThis) [inherited]
Add a new node related to this.
Adds a child after the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 289 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone().
TiXmlNode * RTT::marsh::TiXmlNode::InsertBeforeChild (TiXmlNode * beforeThis, const TiXmlNode & addThis) [inherited]
Add a new node related to this.
Adds a child before the specified child. Returns a pointer to the new object or NULL if an error occured.
Definition at line 263 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone().
TiXmlNode * RTT::marsh::TiXmlNode::InsertEndChild (const TiXmlNode & addThis) [inherited]
Add a new node related to this.
Adds a child past the LastChild. Returns a pointer to the new object or NULL if an error occured.
Definition at line 253 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone(), and RTT::marsh::TiXmlNode::LinkEndChild().
const TiXmlNode * RTT::marsh::TiXmlNode::IterateChildren (const TiXmlNode * previous) const [inherited]
An alternate way to walk the children of a node.
One way to iterate over nodes is:
            for( child = parent->FirstChild(); child; child = child->NextSibling() )
IterateChildren does the same thing with the syntax:
            child = 0;
            while( child = parent->IterateChildren( child ) )
IterateChildren takes the previous child as input and finds the next one. If the previous child is null, it returns the first. IterateChildren will return null when done.
Definition at line 411 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::FirstChild(), and RTT::marsh::TiXmlNode::NextSibling().
TiXmlNode * RTT::marsh::TiXmlNode::LinkEndChild (TiXmlNode * addThis) [inherited]
Add a new node related to this.
Adds a child past the LastChild.
NOTE: the node to be added is passed by pointer, and will be henceforth owned (and deleted) by tinyXml. This method is efficient and avoids an extra copy, but should be used with care as it uses a different memory model than the other insert functions.
See also:
InsertEndChild
Definition at line 233 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::GetDocument().
Referenced by RTT::marsh::TiXmlNode::InsertEndChild(), and RTT::marsh::TiXmlDocument::Parse().
const TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement () const [inherited]
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 574 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
Referenced by RTT::marsh::TiXmlHandle::ChildElement().
const TiXmlElement * RTT::marsh::TiXmlNode::NextSiblingElement (const char * _value) const [inherited]
Convenience function to get through elements.
Calls NextSibling and ToElement. Will skip all non-Element nodes. Returns 0 if there is not another element.
Definition at line 602 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::ToElement().
TiXmlNode * RTT::marsh::TiXmlNode::ReplaceChild (TiXmlNode * replaceThis, const TiXmlNode & withThis) [inherited]
Replace a child of this node.
Returns a pointer to the new object or NULL if an error occured.
Definition at line 315 of file tinyxml.cpp.
References RTT::marsh::TiXmlNode::Clone().
int RTT::marsh::TiXmlBase::Row () const [inline, inherited]
Return the position, in the original source file, of this node or attribute.
The row and column are 1-based. (That is the first row and first column is 1,1). If the returns values are 0 or less, then the parser does not have a row and column value.
Generally, the row and column value will be set when the TiXmlDocument::Load(), TiXmlDocument::LoadFile(), or any TiXmlNode::Parse() is called. It will NOT be set when the DOM was created from operator>>.
The values reflect the initial load. Once the DOM is modified programmatically (by adding or changing nodes and attributes) the new values will NOT update to reflect changes in the document.
There is a minor performance cost to computing the row and column. Computation can be disabled if TiXmlDocument::SetTabSize() is called with 0 as the value.
See also:
TiXmlDocument::SetTabSize()
Definition at line 235 of file tinyxml.h.
static void RTT::marsh::TiXmlBase::SetCondenseWhiteSpace (bool condense) [inline, static, inherited]
The world does not agree on whether white space should be kept or not.
In order to make everyone happy, these global, static functions are provided to set whether or not TinyXml will condense all white space into a single space or not. The default is to condense. Note changing this values is not thread safe.
Definition at line 212 of file tinyxml.h.
void RTT::marsh::TiXmlNode::SetValue (const char * _value) [inline, inherited]
Changes the value of the node.
Defined as:
        Document:    filename of the xml file
        Element:    name of the element
        Comment:    the comment text
        Unknown:    the tag contents
        Text:        the text string
Definition at line 511 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlText::TiXmlText().
int RTT::marsh::TiXmlNode::Type () const [inline, inherited]
Query the type (as an enumerated value, above) of this node.
The possible types are: DOCUMENT, ELEMENT, COMMENT, UNKNOWN, TEXT, and DECLARATION.
Definition at line 664 of file tinyxml.h.
const char* RTT::marsh::TiXmlNode::Value () const [inline, inherited]
The meaning of 'value' changes for the specific type of TiXmlNode.
        Document:    filename of the xml file
        Element:    name of the element
        Comment:    the comment text
        Unknown:    the tag contents
        Text:        the text string
The subclasses will wrap this function.
Definition at line 492 of file tinyxml.h.
Referenced by RTT::marsh::TiXmlElement::Clone(), RTT::marsh::TiXmlNode::FirstChild(), RTT::marsh::TiXmlElement::GetText(), RTT::marsh::TiXmlNode::LastChild(), RTT::marsh::TiXmlNode::NextSibling(), and RTT::marsh::TiXmlNode::PreviousSibling().
Member Data Documentation
const char * RTT::marsh::TiXmlBase::errorString [static, protected, inherited]
Initial value:
{
    "No error",
    "Error",
    "Failed to open file",
    "Memory allocation failed.",
    "Error parsing Element.",
    "Failed to read Element name",
    "Error reading Element value.",
    "Error reading Attributes.",
    "Error: empty tag.",
    "Error reading end tag.",
    "Error parsing Unknown.",
    "Error parsing Comment.",
    "Error parsing Declaration.",
    "Error document empty.",
    "Error null (0) or unexpected EOF found in input stream.",
    "Error parsing CDATA.",
}
Definition at line 373 of file tinyxml.h.
const int RTT::marsh::TiXmlBase::utf8ByteTable [static, inherited]
Initial value:
{
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
}
Definition at line 243 of file tinyxml.h.
The documentation for this class was generated from the following files:
rtt/marsh/tinyxml.h
rtt/marsh/tinyxml.cpp
rtt/marsh/tinyxmlparser.cpp