Orocos Real-Time Toolkit: RTT::scripting::ConditionBoolDataSource Class Reference
RTT::scripting::ConditionBoolDataSource Class Reference
A Condition which holds a boolean DataSource.
#include <rtt/scripting/ConditionBoolDataSource.hpp>
Public Member Functions
ConditionBoolDataSource (internal::DataSource< bool > *s)
The constructor stores the internal::DataSource s in a shared_ptr.
bool evaluate ()
Evaluate the Condition and return the outcome.
ConditionBoolDataSource * clone () const
The Clone Software Pattern.
void reset ()
Some conditions need to be reset at some points.
ConditionBoolDataSource * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
A Condition which holds a boolean DataSource.
Definition at line 55 of file ConditionBoolDataSource.hpp.
Member Function Documentation
ConditionBoolDataSource * RTT::ConditionBoolDataSource::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 61 of file ConditionBoolDataSource.cpp.
References ConditionBoolDataSource(), and RTT::internal::DataSource< T >::copy().
bool RTT::ConditionBoolDataSource::evaluate () [virtual]
Evaluate the Condition and return the outcome.
Returns:
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 46 of file ConditionBoolDataSource.cpp.
References RTT::internal::DataSource< T >::get().
void RTT::ConditionBoolDataSource::reset () [virtual]
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 56 of file ConditionBoolDataSource.cpp.
References RTT::base::DataSourceBase::reset().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionBoolDataSource.hpp
rtt/scripting/ConditionBoolDataSource.cpp