Orocos Real-Time Toolkit: RTT::base::PropertyBagVisitor Class Reference
RTT::base::PropertyBagVisitor Class Reference
A simple introspection interface to visit PropertyBags.
#include <rtt/base/PropertyBagVisitor.hpp>
Public Member Functions
virtual void introspect (PropertyBase *p)=0
Callback for a Property which is not a PropertyBag.
virtual void introspect (Property< PropertyBag > &p)=0
Callback for a Property which is a PropertyBag.
Protected Member Functions
bool introspectAndDecompose (PropertyBase *t)
The default handler to execute when an unknown type is being decomposed.
Detailed Description
A simple introspection interface to visit PropertyBags.
A class which implements this interface can call bag.identify(this);. For each property, introspect(PropertyBase* p) is called, unless the property contains a bag, then introspect(Property<PropertyBag>& p) is called, upon which you may call identify again on it's value(). The marshallers use this technique.
See also:
PropertyIntrospection to have a detailed type lookup of a property.
Deprecated:
DO NOT USE. Will be removed in 2.x release series.
Definition at line 60 of file PropertyBagVisitor.hpp.
Member Function Documentation
bool RTT::PropertyBagVisitor::introspectAndDecompose (PropertyBase * t) [protected]
The default handler to execute when an unknown type is being decomposed.
Returns:
true when it could be decomposed or converted to int or false otherwise.
Definition at line 49 of file PropertyBagVisitor.cpp.
References RTT::types::TypeInfo::buildProperty(), RTT::types::TypeInfo::decomposeType(), RTT::deletePropertyBag(), RTT::base::PropertyBase::getDataSource(), RTT::base::PropertyBase::getDescription(), RTT::base::PropertyBase::getName(), RTT::base::PropertyBase::getTypeInfo(), introspect(), and RTT::types::propertyDecomposition().
The documentation for this class was generated from the following files:
rtt/base/PropertyBagVisitor.hpp
rtt/base/PropertyBagVisitor.cpp