Orocos Real-Time Toolkit: RTT::scripting::ConditionBoolProperty Class Reference
RTT::scripting::ConditionBoolProperty Class Reference
ConditionBoolProperty is a Condition which reads out a Property<bool>.
#include <rtt/scripting/ConditionBoolProperty.hpp>
Public Member Functions
ConditionBoolProperty (const Property< bool > &prop)
bool evaluate ()
Evaluate the Condition and return the outcome.
ConditionBoolProperty * clone () const
The Clone Software Pattern.
std::string toString ()
virtual void reset ()
Some conditions need to be reset at some points.
virtual ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
ConditionBoolProperty is a Condition which reads out a Property<bool>.
Deprecated:
Remove this low-level class since it's nowhere used.
Definition at line 56 of file ConditionBoolProperty.hpp.
Member Function Documentation
ConditionInterface * RTT::ConditionInterface::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [virtual, inherited]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionCache, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionInvert, RTT::scripting::TryCommandResult, and RTT::scripting::EvalCommandResult.
Definition at line 50 of file ConditionInterface.cpp.
Referenced by RTT::scripting::ParsedStateMachine::copy(), and RTT::scripting::DataSourceCondition::copy().
bool RTT::ConditionBoolProperty::evaluate () [virtual]
Evaluate the Condition and return the outcome.
Returns:
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 41 of file ConditionBoolProperty.cpp.
References RTT::Property< T >::get().
void RTT::ConditionInterface::reset () [virtual, inherited]
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented in RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionCache, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionDuration, RTT::scripting::ConditionExpire, and RTT::scripting::ConditionOnce.
Definition at line 47 of file ConditionInterface.cpp.
Referenced by RTT::scripting::Parser::parseCondition(), RTT::scripting::EdgeCondition::reset(), and RTT::scripting::DataSourceCondition::reset().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionBoolProperty.hpp
rtt/scripting/ConditionBoolProperty.cpp