Orocos Real-Time Toolkit: RTT::scripting::TryCommandResult Class Reference
RTT::scripting::TryCommandResult Class Reference
Returns the (accept/reject) status of another command.
#include <rtt/scripting/TryCommand.hpp>
Public Member Functions
TryCommandResult (internal::DataSource< bool >::shared_ptr ec, bool invert)
Pass TryCommand::result() to the first parameter of the command you want to check.
bool evaluate ()
Evaluate the Condition and return the outcome.
ConditionInterface * clone () const
The Clone Software Pattern.
ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual void reset ()
Some conditions need to be reset at some points.
Detailed Description
Returns the (accept/reject) status of another command.
See also:
TryCommand
Definition at line 96 of file TryCommand.hpp.
Constructor & Destructor Documentation
RTT::TryCommandResult::TryCommandResult (internal::DataSource< bool >::shared_ptr ec, bool invert)
Pass TryCommand::result() to the first parameter of the command you want to check.
If invert is true, TryCommandResult::evaluate() will return true if the original command failed. If invert is false, evaluate() will return the return value of the original command.
Definition at line 111 of file TryCommand.cpp.
Referenced by clone(), and copy().
Member Function Documentation
ConditionInterface * RTT::TryCommandResult::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 127 of file TryCommand.cpp.
References RTT::internal::DataSource< T >::copy(), and TryCommandResult().
bool RTT::TryCommandResult::evaluate () [virtual]
Evaluate the Condition and return the outcome.
Returns:
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 118 of file TryCommand.cpp.
References RTT::internal::DataSource< T >::get().
void RTT::ConditionInterface::reset () [virtual, inherited]
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented in RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionCache, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionDuration, RTT::scripting::ConditionExpire, and RTT::scripting::ConditionOnce.
Definition at line 47 of file ConditionInterface.cpp.
Referenced by RTT::scripting::Parser::parseCondition(), RTT::scripting::EdgeCondition::reset(), and RTT::scripting::DataSourceCondition::reset().
The documentation for this class was generated from the following files:
rtt/scripting/TryCommand.hpp
rtt/scripting/TryCommand.cpp