Orocos Real-Time Toolkit: RTT::scripting::SendHandleAlias Class Reference
RTT::scripting::SendHandleAlias Class Reference
Keeps track of a DataSource which has a SendHandle and the factory for creating the collect functions associated with that handle.
#include <rtt/scripting/SendHandleAlias.hpp>
Public Member Functions
SendHandleAlias (const std::string &name, base::DataSourceBase::shared_ptr d, OperationInterfacePart *opf)
base::DataSourceBase::shared_ptr getDataSource () const
Return a internal::DataSource which contains the same contents.
OperationInterfacePart * getFactory () const
SendHandleAlias * clone () const
Returns a clone of this AttributeBase.
SendHandleAlias * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &replacements, bool)
Returns a copy of this AttributeBase.
const std::string & getName () const
Get the name of this instance.
void setName (std::string const &new_name)
Get the name of this instance.
bool ready () const
Returns true if the Attribute was correctly initialised.
Protected Attributes
std::string mname
Detailed Description
Keeps track of a DataSource which has a SendHandle and the factory for creating the collect functions associated with that handle.
Definition at line 54 of file SendHandleAlias.hpp.
Member Function Documentation
SendHandleAlias * RTT::SendHandleAlias::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & replacements, bool instantiate) [virtual]
Returns a copy of this AttributeBase.
Uses the given replacements to copy held DataSources.
Parameters:
instantiate Set to true to get a copy which will return itself on any future copy request.
Implements RTT::base::AttributeBase.
Definition at line 66 of file SendHandleAlias.cpp.
const std::string & RTT::AttributeBase::getName () const [inherited]
Get the name of this instance.
Returns:
the name
Definition at line 59 of file Attribute.cpp.
Referenced by RTT::ConfigurationInterface::getAttributeNames(), RTT::ConfigurationInterface::hasAttribute(), RTT::Constant< T >::operator=(), RTT::Attribute< T >::operator=(), RTT::ConfigurationInterface::removeValue(), and RTT::ConfigurationInterface::setValue().
void RTT::AttributeBase::setName (std::string const & new_name) [inherited]
Get the name of this instance.
Returns:
the name
Definition at line 64 of file Attribute.cpp.
Referenced by RTT::ConfigurationInterface::addAttribute(), and RTT::ConfigurationInterface::addConstant().
The documentation for this class was generated from the following files:
rtt/scripting/SendHandleAlias.hpp
rtt/scripting/SendHandleAlias.cpp