Orocos Real-Time Toolkit: RTT::scripting::ConditionDSDuration Class Reference
RTT::scripting::ConditionDSDuration Class Reference
A conditional that evaluates true after a certain time (in seconds) has passed, given by a DataSource.
#include <rtt/scripting/ConditionDSDuration.hpp>
Public Member Functions
ConditionDSDuration (internal::DataSource< double >::shared_ptr ds, bool invert=false)
Create a condition that changes after ds->get() seconds.
virtual bool evaluate ()
Evaluate the Condition and return the outcome.
virtual void reset ()
Some conditions need to be reset at some points.
ConditionInterface * clone () const
The Clone Software Pattern.
virtual ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
A conditional that evaluates true after a certain time (in seconds) has passed, given by a DataSource.
The behaviour can be inverted upon construction.
Definition at line 56 of file ConditionDSDuration.hpp.
Constructor & Destructor Documentation
RTT::ConditionDSDuration::ConditionDSDuration (internal::DataSource< double >::shared_ptr ds, bool invert = false)
Create a condition that changes after ds->get() seconds.
Parameters:
ds A internal::DataSource containing the period of time starting from reset()
invert If false (default) then the condition will raise to true after ds->get() seconds. If true then the condition will fall to false after ds->get() seconds.
Definition at line 45 of file ConditionDSDuration.cpp.
Referenced by clone(), and copy().
Member Function Documentation
ConditionInterface * RTT::ConditionDSDuration::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 68 of file ConditionDSDuration.cpp.
References ConditionDSDuration(), and RTT::internal::DataSource< T >::copy().
bool RTT::ConditionDSDuration::evaluate () [virtual]
Evaluate the Condition and return the outcome.
Returns:
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 53 of file ConditionDSDuration.cpp.
References RTT::internal::DataSource< T >::get(), and RTT::os::TimeService::secondsSince().
void RTT::ConditionDSDuration::reset () [virtual]
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 58 of file ConditionDSDuration.cpp.
References RTT::os::TimeService::getTicks().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionDSDuration.hpp
rtt/scripting/ConditionDSDuration.cpp