Orocos Real-Time Toolkit: RTT::scripting::ConditionDuration Class Reference
RTT::scripting::ConditionDuration Class Reference
A conditional that evaluates true after a certain time has passed.
#include <rtt/scripting/ConditionDuration.hpp>
Public Member Functions
ConditionDuration (nsecs t, bool invert=false)
Create a condition that changes after t nano seconds.
virtual bool evaluate ()
Evaluate the Condition and return the outcome.
virtual void reset ()
Some conditions need to be reset at some points.
ConditionInterface * clone () const
The Clone Software Pattern.
virtual ConditionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
A conditional that evaluates true after a certain time has passed.
The behaviour can be inverted upon construction.
Definition at line 54 of file ConditionDuration.hpp.
Constructor & Destructor Documentation
RTT::ConditionDuration::ConditionDuration (nsecs t, bool invert = false)
Create a condition that changes after t nano seconds.
Parameters:
t the period of time starting from reset()
invert If false (default) then the condition will raise to true after t. If true then the condition will fall to false after t.
Definition at line 47 of file ConditionDuration.cpp.
Referenced by clone().
Member Function Documentation
ConditionInterface * RTT::ConditionInterface::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [virtual, inherited]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Command that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ConditionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::scripting::ConditionBoolDataSource, RTT::scripting::ConditionCache, RTT::scripting::ConditionCompare< T, compare_op >, RTT::scripting::ConditionBinaryCompositeAND, RTT::scripting::ConditionDSDuration, RTT::scripting::ConditionInvert, RTT::scripting::TryCommandResult, and RTT::scripting::EvalCommandResult.
Definition at line 50 of file ConditionInterface.cpp.
Referenced by RTT::scripting::ParsedStateMachine::copy(), and RTT::scripting::DataSourceCondition::copy().
bool RTT::ConditionDuration::evaluate () [virtual]
Evaluate the Condition and return the outcome.
Returns:
true if the condition is satisfied, false otherwise.
Implements RTT::scripting::ConditionInterface.
Definition at line 55 of file ConditionDuration.cpp.
References RTT::os::TimeService::ticks2nsecs(), and RTT::os::TimeService::ticksSince().
void RTT::ConditionDuration::reset () [virtual]
Some conditions need to be reset at some points.
E.g. a scripting::ConditionDuration counts the time since the first time a Command was executed, and if this time exceeds a certain preset time, returns true. Therefore, it needs to be reset, i.e. it needs to start counting, when the command is first executed.. scripting::ConditionOnce has a similar need. This function is called at such times.
Reimplemented from RTT::scripting::ConditionInterface.
Definition at line 60 of file ConditionDuration.cpp.
References RTT::os::TimeService::getTicks().
The documentation for this class was generated from the following files:
rtt/scripting/ConditionDuration.hpp
rtt/scripting/ConditionDuration.cpp