Orocos Real-Time Toolkit: RTT::scripting::CommandNOP Class Reference
RTT::scripting::CommandNOP Class Reference
The empty command.
#include <rtt/scripting/CommandNOP.hpp>
Public Types
typedef boost::shared_ptr
< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
CommandNOP ()
Create an empty command.
virtual bool execute ()
Execute the functionality of this action.
virtual void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
virtual base::ActionInterface * clone () const
The Clone Software Pattern.
virtual void reset ()
Reset this action.
virtual bool valid () const
Inspect if this action was executed and valid.
virtual ActionInterface * copy (std::map< const DataSourceBase *, DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
Detailed Description
The empty command.
This command does nothing when executed.
Definition at line 52 of file CommandNOP.hpp.
Member Function Documentation
ActionInterface * RTT::ActionInterface::copy (std::map< const DataSourceBase *, DataSourceBase * > & alreadyCloned) const [virtual, inherited]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented in RTT::internal::AssignCommand< T, S >, RTT::scripting::CallFunction, RTT::scripting::CommandComposite, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 60 of file ActionInterface.cpp.
References RTT::base::ActionInterface::clone().
Referenced by RTT::scripting::TryCommand::copy(), RTT::internal::ActionAliasAssignableDataSource< T >::copy(), RTT::internal::ActionAliasDataSource< T >::copy(), and RTT::internal::DataSourceCommand::copy().
bool RTT::CommandNOP::execute () [virtual]
Execute the functionality of this action.
Returns:
true if the action was accepted, false otherwise
Implements RTT::base::ActionInterface.
Definition at line 42 of file CommandNOP.cpp.
void RTT::ActionInterface::reset () [virtual, inherited]
Reset this action.
Must be used after execute() failed.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandCounter, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 50 of file ActionInterface.cpp.
Referenced by RTT::scripting::StateMachine::activate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::scripting::TryCommand::reset(), RTT::internal::DataSourceCommand::reset(), and RTT::scripting::VertexNode::startExecution().
bool RTT::ActionInterface::valid () const [virtual, inherited]
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandComposite, and RTT::scripting::TryCommand.
Definition at line 53 of file ActionInterface.cpp.
Referenced by RTT::scripting::VertexNode::isValid(), and RTT::scripting::TryCommand::valid().
The documentation for this class was generated from the following files:
rtt/scripting/CommandNOP.hpp
rtt/scripting/CommandNOP.cpp