Orocos Real-Time Toolkit: rtt/os/startstop.h File Reference
startstop.h File Reference
Prototype definitions of common os init/exit calls.
#include "../rtt-config.h"
#include <exception>
Functions
RTT_API int __os_init (int argc, char **argv)
Call this function from within main() before using the RTT services.
RTT_API void __os_exit (void)
Call this function from within main() after using the RTT services, just before returning.
RTT_API void __os_printFailure (const char *prog)
Internal: Inform the user that a failure occured.
RTT_API void __os_printException (const char *prog, std::exception &arg)
Internal: Inform the user that a failure occured.
RTT_API int __os_checkException (int &, char **)
Internal: Check if the user requests disabling exception catching at run-time.
RTT_API int __os_main_argc (void)
Call this function to find out how many arguments were passed to the process' main() function.
RTT_API char ** __os_main_argv (void)
Call this function to get the list of arguments of this process' main() function.
Detailed Description
Prototype definitions of common os init/exit calls.
Definition in file startstop.h.
Function Documentation
RTT_API int __os_checkException (int & , char **)
Internal: Check if the user requests disabling exception catching at run-time.
See also:
ORO_main
Definition at line 148 of file startstop.cpp.
RTT_API void __os_exit (void)
Call this function from within main() after using the RTT services, just before returning.
You do not need this when you use ORO_main().
Definition at line 164 of file startstop.cpp.
References RTT::Logger::log(), RTT::os::MainThread::Release(), RTT::os::TimeService::Release(), RTT::Logger::Release(), RTT::types::TypekitRepository::Release(), RTT::types::GlobalsRepository::Release(), and RTT::os::StartStopManager::stop().
RTT_API int __os_init (int argc, char ** argv)
Call this function from within main() before using the RTT services.
You do not need this when you use ORO_main().
Definition at line 76 of file startstop.cpp.
References RTT::dev::NameServer< _ValueType >::getObject(), RTT::os::MainThread::Instance(), RTT::Logger::log(), RTT::dev::DigitalOutInterface::nameserver, RTT::os::StartStopManager::start(), and RTT::dev::DigitalOutInterface::switchOn().
RTT_API void __os_printException (const char * prog, std::exception & arg)
Internal: Inform the user that a failure occured.
See also:
ORO_main
Definition at line 137 of file startstop.cpp.
References RTT::os::endl().
RTT_API void __os_printFailure (const char * prog)
Internal: Inform the user that a failure occured.
See also:
ORO_main
Definition at line 118 of file startstop.cpp.
References RTT::os::endl().