Orocos Real-Time Toolkit: RTT::scripting::CommandDataSourceBool Struct Reference
RTT::scripting::CommandDataSourceBool Struct Reference
A Command which evaluates a internal::DataSource<bool> and returns the result of get().
#include <rtt/scripting/CommandDataSource.hpp>
Public Types
typedef boost::shared_ptr
< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
CommandDataSourceBool (internal::DataSource< bool >::shared_ptr dsb)
void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
bool execute ()
Execute the functionality of this action.
void reset ()
Reset this action.
base::ActionInterface * clone () const
The Clone Software Pattern.
base::ActionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual bool valid () const
Inspect if this action was executed and valid.
Public Attributes
internal::DataSource< bool >
::shared_ptr _dsb
Detailed Description
A Command which evaluates a internal::DataSource<bool> and returns the result of get().
Definition at line 84 of file CommandDataSource.hpp.
Member Function Documentation
base::ActionInterface* RTT::scripting::CommandDataSourceBool::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [inline, virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::base::ActionInterface.
Definition at line 106 of file CommandDataSource.hpp.
References RTT::internal::DataSource< T >::copy().
bool RTT::scripting::CommandDataSourceBool::execute () [inline, virtual]
Execute the functionality of this action.
Returns:
true if the action was accepted, false otherwise
Implements RTT::base::ActionInterface.
Definition at line 96 of file CommandDataSource.hpp.
References RTT::internal::DataSource< T >::value().
void RTT::scripting::CommandDataSourceBool::reset () [inline, virtual]
Reset this action.
Must be used after execute() failed.
Reimplemented from RTT::base::ActionInterface.
Definition at line 99 of file CommandDataSource.hpp.
References RTT::base::DataSourceBase::reset().
bool RTT::ActionInterface::valid () const [virtual, inherited]
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandComposite, and RTT::scripting::TryCommand.
Definition at line 53 of file ActionInterface.cpp.
Referenced by RTT::scripting::VertexNode::isValid(), and RTT::scripting::TryCommand::valid().
The documentation for this struct was generated from the following file:
rtt/scripting/CommandDataSource.hpp