Orocos Real-Time Toolkit: RTT::internal::AssignCommand< T, S > Class Template Reference
RTT::internal::AssignCommand< T, S > Class Template Reference
This is a command that will assign the value of an expression to another at runtime.
#include <rtt/internal/AssignCommand.hpp>
Public Types
typedef AssignableDataSource
< T >::shared_ptr LHSSource
typedef DataSource< S >::const_ptr RHSSource
typedef boost::shared_ptr
< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
AssignCommand (LHSSource l, RHSSource r)
Assign r (rvalue) to l (lvalue);.
void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
bool execute ()
Execute the functionality of this action.
virtual base::ActionInterface * clone () const
The Clone Software Pattern.
virtual base::ActionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual void reset ()
Reset this action.
virtual bool valid () const
Inspect if this action was executed and valid.
Detailed Description
template<typename T, typename S = T>
class RTT::internal::AssignCommand< T, S >
This is a command that will assign the value of an expression to another at runtime.
You pass it the AssignableDataSource that you want to assign to, and the DataSource that you want to assign on construction, and it will take care of the assignment. Note that both DataSource's need to be of a convertible type, and this class needs that type as its template parameter..
Parameters:
T Target type
S Source type
Definition at line 60 of file AssignCommand.hpp.
Member Function Documentation
template<typename T, typename S = T> virtual base::ActionInterface* RTT::internal::AssignCommand< T, S >::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [inline, virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::base::ActionInterface.
Definition at line 98 of file AssignCommand.hpp.
References RTT::internal::AssignCommand< T, S >::AssignCommand().
template<typename T, typename S = T> bool RTT::internal::AssignCommand< T, S >::execute () [inline, virtual]
Execute the functionality of this action.
Returns:
true if the action was accepted, false otherwise
Implements RTT::base::ActionInterface.
Definition at line 83 of file AssignCommand.hpp.
void RTT::ActionInterface::reset () [virtual, inherited]
Reset this action.
Must be used after execute() failed.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandCounter, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 50 of file ActionInterface.cpp.
Referenced by RTT::scripting::StateMachine::activate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::scripting::TryCommand::reset(), RTT::internal::DataSourceCommand::reset(), and RTT::scripting::VertexNode::startExecution().
bool RTT::ActionInterface::valid () const [virtual, inherited]
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandComposite, and RTT::scripting::TryCommand.
Definition at line 53 of file ActionInterface.cpp.
Referenced by RTT::scripting::VertexNode::isValid(), and RTT::scripting::TryCommand::valid().
The documentation for this class was generated from the following file:
rtt/internal/AssignCommand.hpp