Orocos Real-Time Toolkit: RTT::base::ExecutableInterface Class Reference
RTT::base::ExecutableInterface Class Reference
Objects that implement this interface are to be executed in the ExecutionEngine.
#include <rtt/base/ExecutableInterface.hpp>
Public Member Functions
void loaded (ExecutionEngine *ee)
Called by the ExecutionEngine ee to tell this object it is being loaded.
void unloaded ()
Called by the ExecutionEngine ee to tell this object it is being unloaded.
virtual void loading ()
Informs this object that it got loaded in an ExecutionEngine.
bool isLoaded ()
Returns true if this object is loaded in an ExecutionEngine.
ExecutionEngine * getEngine ()
Returns the ExecutionEngine this object is loaded into or null otherwise.
virtual bool execute ()=0
Executes a piece of functionality.
virtual void unloading ()
Informs this object that it got unloaded from an ExecutionEngine.
Protected Attributes
ExecutionEngine * engine
Detailed Description
Objects that implement this interface are to be executed in the ExecutionEngine.
One can insert and remove objects that implement this interface safely in and out the ExecutionEngine.
Be careful that all these functions may be called from a hard real-time context.
Definition at line 58 of file ExecutableInterface.hpp.
Member Function Documentation
virtual bool RTT::base::ExecutableInterface::execute () [pure virtual]
Executes a piece of functionality.
Called by the ExecutionEngine directly.
Returns:
false if this object should no longer be executed.
Implemented in RTT::scripting::FunctionGraph, RTT::scripting::ProgramInterface, and RTT::scripting::StateMachine.
ExecutionEngine* RTT::base::ExecutableInterface::getEngine () [inline]
Returns the ExecutionEngine this object is loaded into or null otherwise.
Returns:
Definition at line 102 of file ExecutableInterface.hpp.
Referenced by RTT::scripting::StateMachine::loading(), and RTT::scripting::StateMachine::~StateMachine().
bool RTT::base::ExecutableInterface::isLoaded () [inline]
Returns true if this object is loaded in an ExecutionEngine.
Returns:
true if so.
Definition at line 95 of file ExecutableInterface.hpp.
Referenced by RTT::scripting::FunctionGraph::pause(), RTT::ExecutionEngine::removeFunction(), RTT::scripting::FunctionGraph::start(), RTT::scripting::FunctionGraph::step(), and RTT::scripting::StateMachine::~StateMachine().
void RTT::base::ExecutableInterface::loaded (ExecutionEngine * ee) [inline]
Called by the ExecutionEngine ee to tell this object it is being loaded.
The engine pointer is set first and the user's loading() function is called next.
Parameters:
ee The pointer to the engine calling us.
Definition at line 70 of file ExecutableInterface.hpp.
Referenced by RTT::ExecutionEngine::runFunction().
virtual void RTT::base::ExecutableInterface::loading () [inline, virtual]
Informs this object that it got loaded in an ExecutionEngine.
Called by load() after the engine pointer is set.
Reimplemented in RTT::scripting::FunctionGraph, and RTT::scripting::StateMachine.
Definition at line 89 of file ExecutableInterface.hpp.
void RTT::base::ExecutableInterface::unloaded () [inline]
Called by the ExecutionEngine ee to tell this object it is being unloaded.
The user's loading() function is called first and the engine pointer is cleared next.
Definition at line 78 of file ExecutableInterface.hpp.
Referenced by RTT::ExecutionEngine::removeFunction().
virtual void RTT::base::ExecutableInterface::unloading () [inline, virtual]
Informs this object that it got unloaded from an ExecutionEngine.
Called by unload() before the engine pointer is cleared.
Reimplemented in RTT::scripting::FunctionGraph, RTT::scripting::ParsedStateMachine, and RTT::scripting::StateMachine.
Definition at line 118 of file ExecutableInterface.hpp.
The documentation for this class was generated from the following file:
rtt/base/ExecutableInterface.hpp