Orocos Real-Time Toolkit: RTT::types::TransportPlugin Class Reference
RTT::types::TransportPlugin Class Reference
A class which registers TypeTransporter instances to types.
#include <rtt/types/TransportPlugin.hpp>
Public Member Functions
virtual bool registerTransport (std::string type_name, TypeInfo *ti)=0
Add a transport for the given type to the types::TypeInfo instance.
virtual std::string getTransportName () const =0
Returns the (protocol) name of this transport.
virtual std::string getTypekitName () const =0
Returns the intended typekit name of this plugin.
virtual std::string getName () const =0
Each plugin must have a unique name.
Detailed Description
A class which registers TypeTransporter instances to types.
Use the ORO_TYPEKIT_PLUGIN macro to have the plugin framework automatically load all types supported by this plugin (using registerTransport() below).
A transport's 'fully qualified name' consists of the protocol name followed by a "://" and the name of the typekit it is for. For example:
"CORBA://kdl-types/frame". The protocol name may not contain slashes.
Definition at line 56 of file TransportPlugin.hpp.
Member Function Documentation
virtual std::string RTT::types::TransportPlugin::getName () const [pure virtual]
Each plugin must have a unique name.
This name is used globally in the process to identify this instance.
Implemented in RTT::corba::CorbaLibPlugin, RTT::mqueue::MQLibPlugin, and RTT::mqueue::MQLibPlugin.
Referenced by RTT::types::TypekitRepository::Import().
virtual std::string RTT::types::TransportPlugin::getTransportName () const [pure virtual]
Returns the (protocol) name of this transport.
May not contain slashes. e.g. "CORBA", "mqueue, "rostcp",...
Implemented in RTT::corba::CorbaLibPlugin, RTT::mqueue::MQLibPlugin, and RTT::mqueue::MQLibPlugin.
Referenced by RTT::types::TypekitRepository::Import(), and RTT::types::TypeInfoRepository::registerTransport().
virtual std::string RTT::types::TransportPlugin::getTypekitName () const [pure virtual]
Returns the intended typekit name of this plugin.
This is informative and only for user display. e.g. "rtt-types", "kdl-types/frame",...
Implemented in RTT::corba::CorbaLibPlugin, RTT::mqueue::MQLibPlugin, and RTT::mqueue::MQLibPlugin.
Referenced by RTT::types::TypekitRepository::Import().
virtual bool RTT::types::TransportPlugin::registerTransport (std::string type_name, TypeInfo * ti) [pure virtual]
Add a transport for the given type to the types::TypeInfo instance.
Parameters:
type_name The name of the type to transport
ti The type to which transports may be added.
Returns:
false if no transport was added, true otherwise.
Implemented in RTT::corba::CorbaLibPlugin, RTT::mqueue::MQLibPlugin, and RTT::mqueue::MQLibPlugin.
Referenced by RTT::types::TypeInfoRepository::registerTransport().
The documentation for this class was generated from the following file:
rtt/types/TransportPlugin.hpp