Orocos Real-Time Toolkit: RTT::OperationInterfacePart Class Reference
RTT::OperationInterfacePart Class Reference
This class defines the interface for creating operation objects without using C++ templates.
#include <rtt/OperationInterfacePart.hpp>
Public Member Functions
virtual std::string getName () const =0
Returns the name of this operation.
virtual std::string description () const =0
Returns the description of this operation.
virtual std::vector
< ArgumentDescription > getArgumentList () const =0
Get a description of the desired arguments in the ArgumentDescription format.
virtual std::string resultType () const =0
Return the result (return) type of this operation.
virtual unsigned int arity () const =0
Returns the arity (number of arguments) of this operation.
virtual const types::TypeInfo * getArgumentType (unsigned int arg) const =0
Returns the type information of the n'th argument, with argument zero being the return value.
virtual unsigned int collectArity () const =0
Returns the number of collectable arguments of this operation's function.
virtual const types::TypeInfo * getCollectType (unsigned int arg) const =0
Returns the type information of the n'th collectable argument.
virtual
base::DataSourceBase::shared_ptr produce (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const =0
Create a DataSource for a given callable operation.
virtual
base::DataSourceBase::shared_ptr produceSend (const std::vector< base::DataSourceBase::shared_ptr > &args, ExecutionEngine *caller) const =0
Create a DataSource for a given send operation.
virtual
base::DataSourceBase::shared_ptr produceHandle () const =0
Create an empty SendHandle object for this operation.
virtual
base::DataSourceBase::shared_ptr produceCollect (const std::vector< base::DataSourceBase::shared_ptr > &args, internal::DataSource< bool >::shared_ptr blocking) const =0
Create a DataSource for collecting the results of a Send.
virtual RTT_API
boost::shared_ptr
< base::DisposableInterface > getLocalOperation () const
Returns any local operation associated with this operation.
Detailed Description
This class defines the interface for creating operation objects without using C++ templates.
The OperationInterface offers the same interface as this class, but with operation names as first argument of each function.
It is most used in conjunction with the OperationCallerC/SendHandleC classes to create objects that manage calling/sending methods and collecting results of method invocations.
A Part must be interpreted as one single operation of an OperationInterface.
This class serves as a base class for the template based classes that implement the produce and query logic for a given operation.
Definition at line 69 of file OperationInterfacePart.hpp.
Member Function Documentation
virtual unsigned int RTT::OperationInterfacePart::arity () const [pure virtual]
Returns the arity (number of arguments) of this operation.
See also:
produce, produceSend
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual unsigned int RTT::OperationInterfacePart::collectArity () const [pure virtual]
Returns the number of collectable arguments of this operation's function.
These consist of the return value and the reference arguments.
See also:
produceCollect
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual std::string RTT::OperationInterfacePart::description () const [pure virtual]
Returns the description of this operation.
Returns:
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual const types::TypeInfo* RTT::OperationInterfacePart::getArgumentType (unsigned int arg) const [pure virtual]
Returns the type information of the n'th argument, with argument zero being the return value.
Parameters:
arg 0: get return value type, 1..arity(): get n'th argument type.
Returns:
A TypeInfo Object or null if
is out of range
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual const types::TypeInfo* RTT::OperationInterfacePart::getCollectType (unsigned int arg) const [pure virtual]
Returns the type information of the n'th collectable argument.
The numbering of arg starts from 1.
Parameters:
arg 1..collectArity(): get n'th argument type.
Returns:
A TypeInfo Object or null if
is out of range
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
boost::shared_ptr< base::DisposableInterface > OperationInterfacePart::getLocalOperation () const [virtual]
Returns any local operation associated with this operation.
Returns:
null if no such operation exists, the operation's implementation otherwise.
Reimplemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, and RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >.
Definition at line 53 of file OperationInterface.cpp.
Referenced by RTT::OperationCaller< int(const std::string &)>::OperationCaller(), RTT::OperationCaller< int(const std::string &)>::operator=(), and RTT::Service::setOperationThread().
virtual std::string RTT::OperationInterfacePart::getName () const [pure virtual]
Returns the name of this operation.
Returns:
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
Referenced by RTT::OperationCaller< int(const std::string &)>::OperationCaller().
virtual base::DataSourceBase::shared_ptr RTT::OperationInterfacePart::produce (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const [pure virtual]
Create a DataSource for a given callable operation.
Parameters:
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed, in case it runs in the owner's thread. Normally, this is the engine of the caller's TaskContext.
Returns:
a DataSource which will return the result of this operation.
Exceptions:
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual base::DataSourceBase::shared_ptr RTT::OperationInterfacePart::produceCollect (const std::vector< base::DataSourceBase::shared_ptr > & args, internal::DataSource< bool >::shared_ptr blocking) const [pure virtual]
Create a DataSource for collecting the results of a Send.
Parameters:
args A vector of data sources of which the first element contains a properly initialised sendhandle and the remainder of the elements contains datasources for collecting the return value and reference arguments. The total number of items in args must be collectArity() + 1
blocking Set to true to do a blocking collect, false for a polling version.
Returns:
A DataSource which collects the results when evaluated and which returns the SendStatus.
Exceptions:
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual base::DataSourceBase::shared_ptr RTT::OperationInterfacePart::produceHandle () const [pure virtual]
Create an empty SendHandle object for this operation.
Returns:
a DataSource which contains an empty SendHandle.
Exceptions:
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
virtual base::DataSourceBase::shared_ptr RTT::OperationInterfacePart::produceSend (const std::vector< base::DataSourceBase::shared_ptr > & args, ExecutionEngine * caller) const [pure virtual]
Create a DataSource for a given send operation.
Parameters:
args The arguments for the target object's function. The number of arguments must be identical to this->arity()
caller The Engine that will receive notifications when the method has been executed. Normally, this is the engine of the caller's TaskContext.
Returns:
a DataSource which contains the SendHandle of this operation.
See also:
produceHandle
Exceptions:
wrong_number_of_args_exception
wrong_types_of_args_exception
name_not_found_exception
no_asynchronous_operation_exception
Implemented in RTT::internal::OperationInterfacePartFused< Signature >, RTT::internal::SynchronousOperationInterfacePartFused< Signature >, RTT::internal::OperationInterfacePartFusedDS< Signature, ObjT >, RTT::scripting::FunctionFactory, and RTT::corba::CorbaOperationCallerFactory.
The documentation for this class was generated from the following files:
rtt/OperationInterfacePart.hpp
rtt/OperationInterface.cpp