Orocos Real-Time Toolkit: RTT::base::DataObjectUnSync< T > Class Template Reference
RTT::base::DataObjectUnSync< T > Class Template Reference
Data Storage and Buffering classes.
A class which provides unprotected (not thread-safe) access to one typed element of data.
#include <rtt/base/DataObjectUnSync.hpp>
Public Types
typedef T DataType
The type of the data.
typedef boost::shared_ptr
< DataObjectInterface< T > > shared_ptr
Used for shared_ptr management.
Public Member Functions
DataObjectUnSync (const T &initial_value=T())
Construct a DataObjectUnSync by name.
virtual void Get (DataType &pull) const
Get a copy of the Data of this data object.
virtual DataType Get () const
Get a copy of the data of this data object.
virtual void Set (const DataType &push)
Set the data to a certain value.
virtual void data_sample (const DataType &sample)
Provides a data sample to initialize this data object.
Detailed Description
template<class T>
class RTT::base::DataObjectUnSync< T >
A class which provides unprotected (not thread-safe) access to one typed element of data.
Definition at line 55 of file DataObjectUnSync.hpp.
Constructor & Destructor Documentation
template<class T > RTT::base::DataObjectUnSync< T >::DataObjectUnSync (const T & initial_value = T()) [inline]
Construct a DataObjectUnSync by name.
Parameters:
_name The name of this DataObject.
Definition at line 68 of file DataObjectUnSync.hpp.
Member Function Documentation
template<class T > virtual void RTT::base::DataObjectUnSync< T >::data_sample (const DataType & sample) [inline, virtual]
Provides a data sample to initialize this data object.
As such enough storage space can be allocated before the actual writing begins.
Parameters:
sample
Implements RTT::base::DataObjectInterface< T >.
Definition at line 82 of file DataObjectUnSync.hpp.
References RTT::base::DataObjectUnSync< T >::Set().
template<class T > virtual DataType RTT::base::DataObjectUnSync< T >::Get () const [inline, virtual]
Get a copy of the data of this data object.
Returns:
A copy of the data.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 78 of file DataObjectUnSync.hpp.
References RTT::base::DataObjectUnSync< T >::Get().
Referenced by RTT::base::DataObjectUnSync< T >::Get().
template<class T > virtual void RTT::base::DataObjectUnSync< T >::Get (DataType & pull) const [inline, virtual]
Get a copy of the Data of this data object.
Parameters:
pull A copy of the data.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 76 of file DataObjectUnSync.hpp.
template<class T > virtual void RTT::base::DataObjectUnSync< T >::Set (const DataType & push) [inline, virtual]
Set the data to a certain value.
Parameters:
push The data which must be set.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 80 of file DataObjectUnSync.hpp.
Referenced by RTT::base::DataObjectUnSync< T >::data_sample().
The documentation for this class was generated from the following file:
rtt/base/DataObjectUnSync.hpp