Orocos Real-Time Toolkit: RTT::scripting::VertexNode Class Reference
RTT::scripting::VertexNode Class Reference
This class represents elements in a program tree.
#include <rtt/scripting/VertexNode.hpp>
Public Types
enum NodeTypes {
normal_node, prog_start_node, prog_exit_node, func_start_node,
func_exit_node
}
The vertex_exec_t property values.
typedef boost::property
< vertex_command_t, VertexNode,
boost::property< vertex_exec_t,
int, boost::property
< boost::vertex_index_t, int > > > VertProperty
Public Member Functions
VertexNode ()
Construct an empty program node with no command, no conditional branches and line number 0.
VertexNode (base::ActionInterface *cmd)
Construct a program node with given command, no conditional branches and line number 0.
VertexNode (const VertexNode &orig)
The copy constructor creates a shallow copy.
VertexNode copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &rdss) const
VertexNode & operator= (const VertexNode &orig)
~VertexNode ()
Returns a special program node that contains no clauses and a special stopExecution command.
void startExecution ()
This means that the execution engine has just started to execute this node, after some other node has sent it to this one.
bool execute ()
Executes the command currently associated with this node.
bool isValid () const
Returns true if the node is in a valid state to be left.
base::ActionInterface * setCommand (base::ActionInterface *c)
Set the command associated with this program to the given command.
void setLineNumber (int ln)
Set line number of this program node to given line number.
base::ActionInterface * getCommand () const
Returns the command currently associated with this node.
int getLineNumber () const
Returns the program line number currently associated with this program node (default = zero).
Detailed Description
This class represents elements in a program tree.
Definition at line 76 of file VertexNode.hpp.
Constructor & Destructor Documentation
RTT::VertexNode::~VertexNode ()
Returns a special program node that contains no clauses and a special stopExecution command.
(all the leaves of a program tree are this type of program node.
Parameters:
proc The engine executing this node (which will be stopped)
Returns:
A program node with no conditional branches and that contains a stop execution command.
Definition at line 64 of file VertexNode.cpp.
Member Function Documentation
bool RTT::VertexNode::execute ()
Executes the command currently associated with this node.
Execute the command in any case. If the command is Asynch, this will do nothing.
Definition at line 70 of file VertexNode.cpp.
References RTT::base::ActionInterface::execute().
ActionInterface * RTT::VertexNode::getCommand () const
Returns the command currently associated with this node.
Returns:
The command currently associated with this node
Definition at line 83 of file VertexNode.cpp.
ActionInterface * RTT::VertexNode::setCommand (base::ActionInterface * c)
Set the command associated with this program to the given command.
Parameters:
c The new command.
Returns:
The previous command (can be null).
Definition at line 88 of file VertexNode.cpp.
void RTT::VertexNode::setLineNumber (int ln)
Set line number of this program node to given line number.
Parameters:
ln The new line number for this node
Postcondition:
The line number of this node equals the given integer.
Definition at line 95 of file VertexNode.cpp.
void RTT::VertexNode::startExecution ()
This means that the execution engine has just started to execute this node, after some other node has sent it to this one.
If the node is simply executed again, because it returned itself from its execute() method, then this method will not be called. The reason this is here is because the node has to reset its termination conditions at this point. See the documentation of ConditionInterface::reset() for more information about this..
Definition at line 105 of file VertexNode.cpp.
References RTT::base::ActionInterface::readArguments(), and RTT::base::ActionInterface::reset().
The documentation for this class was generated from the following files:
rtt/scripting/VertexNode.hpp
rtt/scripting/VertexNode.cpp