Orocos Real-Time Toolkit: RTT::CleanupHandle Class Reference
RTT::CleanupHandle Class Reference
A connection Handle of a (connected) slot which disconnects and cleans up (free all resources) the connection object in its destructor.
#include <rtt/Handle.hpp>
Public Member Functions
CleanupHandle (const Handle &hs)
~CleanupHandle ()
Cleanup all signal and slot connection resources.
bool connect ()
(Re-)Connect the slot with the signal.
bool disconnect ()
Disconnect the slot from the signal.
bool connected () const
Inspect if this Handle represents a connected signal and slot.
operator bool () const
Inspect if this Handle is pointing to a valid (existing) connection.
bool ready () const
Inspect if this handle is pointing to valid (existing) connection(s).
Protected Attributes
connection_t m_conn
This is actually a smart pointer which always points to an existing connection object.
Detailed Description
A connection Handle of a (connected) slot which disconnects and cleans up (free all resources) the connection object in its destructor.
After CleanupHandle was destroyed, the connection is no longer usable and all associated callbacks have been removed. If another Handle object shares the same connection, it will no longer be able to connect().
Definition at line 163 of file Handle.hpp.
Constructor & Destructor Documentation
RTT::CleanupHandle::~CleanupHandle ()
Cleanup all signal and slot connection resources.
If connected, disconnect the slot from the signal. Calls connection::destroy() on the connection object.
Definition at line 107 of file Handle.cpp.
References RTT::Handle::m_conn.
Member Function Documentation
bool RTT::Handle::connect () [inherited]
(Re-)Connect the slot with the signal.
Return values:
true the slot is connected.
false no valid signal or slot in this Handle
Definition at line 65 of file Handle.cpp.
References RTT::Handle::connected(), and RTT::Handle::m_conn.
bool RTT::Handle::connected () const [inherited]
Inspect if this Handle represents a connected signal and slot.
Returns:
true if a connection is present.
Definition at line 79 of file Handle.cpp.
References RTT::Handle::m_conn.
Referenced by RTT::Handle::connect(), and RTT::Handle::disconnect().
bool RTT::Handle::disconnect () [inherited]
Disconnect the slot from the signal.
Return values:
true the slot is disconnected.
false no valid signal or slot in this Handle
Definition at line 72 of file Handle.cpp.
References RTT::Handle::connected(), and RTT::Handle::m_conn.
Referenced by RTT::ScopedHandle::~ScopedHandle().
RTT::Handle::operator bool () const [inherited]
Inspect if this Handle is pointing to a valid (existing) connection.
Returns:
false if no connection is associated with this Handle.
Definition at line 83 of file Handle.cpp.
References RTT::Handle::m_conn.
bool RTT::Handle::ready () const [inherited]
Inspect if this handle is pointing to valid (existing) connection(s).
Returns:
false if no connection(s) is associated with this handle.
Definition at line 87 of file Handle.cpp.
References RTT::Handle::m_conn.
Referenced by RTT::scripting::StateMachine::createEventTransition().
The documentation for this class was generated from the following files:
rtt/Handle.hpp
rtt/Handle.cpp