Orocos Real-Time Toolkit: RTT::PropertyBag Class Reference
RTT::PropertyBag Class Reference
Property Interface
A container for holding references to properties.
#include <rtt/PropertyBag.hpp>
Classes
struct FindPropType
A function object for finding a Property by name and type.
Public Types
typedef std::vector
< base::PropertyBase * > Properties
The container in which the properties are stored.
typedef Properties PropertyContainerType
Deprecated, use Properties.
typedef Properties::iterator iterator
An iterator over the Properties.
typedef Properties::const_iterator const_iterator
A const iterator over the Properties.
typedef std::vector< std::string > Names
The container to hold names of Properties.
Public Member Functions
PropertyBag ()
The default constructor.
PropertyBag (const std::string &_type)
The typed constructor.
PropertyBag (const PropertyBag &orig)
The copy constructor.
~PropertyBag ()
Destroy this object and destroy all owned properties.
void add (base::PropertyBase *p)
Add a valid property to the container.
void remove (base::PropertyBase *p)
Remove a property from the container.
template<class T >
Property< T > & addProperty (const std::string &name, T &attr)
Adds a variable of any type as a property to this bag.
bool addProperty (base::PropertyBase &p)
Add a valid property to the container.
bool removeProperty (base::PropertyBase *p)
Remove a property from the container.
bool ownProperty (base::PropertyBase *p)
Set a property to be owned by this bag.
bool ownsProperty (base::PropertyBase *p) const
Returns true if this property is owned by this Bag.
void clear ()
Removes all PropertyBases from this bag, without deleting them.
void list (Names &names) const
List the names of all properties.
Names list () const
List the names of all properties.
bool empty () const
Return true if no properties are present in this bag.
base::PropertyBase * getProperty (const std::string &name) const
Get a Property with name name.
template<class T >
Property< T > * getPropertyType (const std::string &name) const
Get the first Property with name name of a given type T.
base::PropertyBase * getItem (int i) const
Returns the i'th Property, starting from 0.
size_t size () const
Get the number of Properties in this bag.
void identify (base::PropertyIntrospection *pi) const
Identify the contents of this bag through introspection.
void identify (base::PropertyBagVisitor *pi) const
Identify the contents of this bag through introspection.
base::PropertyBase * find (const std::string &name) const
Find the base::PropertyBase with name name.
template<class T >
base::PropertyBase * findValue (const T &value) const
Finds the base::PropertyBase by value.
PropertyBag & operator= (const PropertyBag &orig)
This assignment assigns all PropertyBases of another bag in this bag, making an exact copy or the original.
PropertyBag & operator<<= (const PropertyBag &source)
The update operator.
PropertyBag & operator<< (base::PropertyBase *item)
The 'add' operator.
const std::string & getType () const
void setType (const std::string &newtype)
Properties & getProperties ()
Returns a list of all the property objects in this bag.
const Properties & getProperties () const
Returns a list of all the property objects in this bag.
Properties getProperties (const std::string &name) const
Returns a list of all property objects with the name name.
Names getPropertyNames () const
Returns a list of all the names of the properties in this bag.
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
Protected Attributes
Properties mproperties
Properties mowned_props
std::string type
Detailed Description
A container for holding references to properties.
Introduction
This class groups properties of different types into a single container. A PropertyBag object can handed to a marsh::Marshaller object which will serialize the contents of the PropertyBag.
All operations on a PropertyBag are non recursive. The PropertyBag itself is not aware of the possible hierarchical structure. You need to use the global scope functions for handling hierarchical structures.
A PropertyBag is not the owner of the properties within. It defines a group of properties, nothing more. When this group of properties contains another PropertyBag, this bag is considered as a 'pointer' to other properties. Even such a bag is not owned by the PropertyBag.
Constructing PropertyBags
It can happen in an application that a PropertyBag is filled with dynamically created Property objects. The bag is not responsible for cleaning up these objects once they are no longer needed. The application which uses the PropertyBag has to find a way of deleting the possible dangling pointers.
Warning:
The elements in a PropertyBag are unordered. Operations on the bag may change the relative order of the elements.
Using PropertyBags
To add a Property<ClassT> prop to a PropertyBag bag, use
     bag.add(&prop).
To retrieve this property, either use find or getProperty to retrieve a Property by name :
     base::PropertyBase* pb = bag.find( "name" ).
     Property<ClassT> pb = bag.getProperty( "name" ).
Both will return null if no such property exists.
See also:
base::PropertyBase, Property, Recursive Property Bag Operations.
Definition at line 96 of file PropertyBag.hpp.
Constructor & Destructor Documentation
RTT::PropertyBag::PropertyBag (const std::string & _type)
The typed constructor.
Parameters:
type The type of PropertyBag.
Definition at line 58 of file PropertyBag.cpp.
RTT::PropertyBag::PropertyBag (const PropertyBag & orig)
The copy constructor.
The copy constructor of the PropertyBag makes non-deep copies of its elements.
Definition at line 62 of file PropertyBag.cpp.
References add(), RTT::base::PropertyBase::clone(), ownProperty(), and ownsProperty().
Member Function Documentation
void RTT::PropertyBag::add (base::PropertyBase * p)
Add a valid property to the container.
Analogous to addProperty.
Parameters:
p Pointer to the property to be added.
Definition at line 80 of file PropertyBag.cpp.
References addProperty().
Referenced by RTT::copyProperties(), RTT::flattenPropertyBag(), RTT::marsh::PropertyBagIntrospector::introspect(), operator<<=(), operator=(), PropertyBag(), and RTT::updateProperties().
bool RTT::PropertyBag::addProperty (base::PropertyBase & p)
Add a valid property to the container.
Parameters:
p Pointer to the property to be added.
Returns:
false if !p || !p->ready(), true otherwise.
Definition at line 112 of file PropertyBag.cpp.
References RTT::base::PropertyBase::ready().
template<class T > Property<T>& RTT::PropertyBag::addProperty (const std::string & name, T & attr) [inline]
Adds a variable of any type as a property to this bag.
A Property is created which causes contents of the property always to be in sync with the contents of attr.
Parameters:
name The name of this property
attr The variable that will be aliased.
Returns:
the Property object by reference, which you can further query or document.
Definition at line 166 of file PropertyBag.hpp.
Referenced by add().
void RTT::PropertyBag::clear ()
Removes all PropertyBases from this bag, without deleting them.
This is a not recursive function.
Definition at line 139 of file PropertyBag.cpp.
Referenced by RTT::deleteProperties(), RTT::deletePropertyBag(), operator=(), and ~PropertyBag().
PropertyBase * RTT::PropertyBag::find (const std::string & name) const
Find the base::PropertyBase with name name.
This function returns the first match.
Parameters:
name The name of the property to search for.
Returns:
The base::PropertyBase with this name, zero if it does not exist.
Definition at line 217 of file PropertyBag.cpp.
Referenced by RTT::extras::composeProperty(), RTT::types::SequenceTypeInfoBase< std::vector< double > >::composeType(), RTT::findProperty(), operator<<=(), ownsProperty(), RTT::refreshProperties(), RTT::refreshProperty(), RTT::removeProperty(), removeProperty(), RTT::storeProperty(), and RTT::updateProperty().
template<class T > base::PropertyBase* RTT::PropertyBag::findValue (const T & value) const [inline]
Finds the base::PropertyBase by value.
This function returns the first match.
Parameters:
value The value the Property should have
T The data type of the value.
Returns:
a pointer to the property or zero if not found.
Definition at line 295 of file PropertyBag.hpp.
References RTT::base::PropertyBase::ready(), and RTT::Property< T >::value().
base::PropertyBase* RTT::PropertyBag::getItem (int i) const [inline]
Returns the i'th Property, starting from 0.
Returns:
zero if i is out of range.
Definition at line 254 of file PropertyBag.hpp.
Referenced by RTT::types::composeProperty(), RTT::operator<<(), and RTT::refreshProperties().
base::PropertyBase * RTT::PropertyBag::getProperty (const std::string & name) const
Get a Property with name name.
Parameters:
name The name of the property to search for.
Returns:
The PropertyBase with this name, zero if it does not exist.
Definition at line 225 of file PropertyBag.cpp.
template<class T > Property<T>* RTT::PropertyBag::getPropertyType (const std::string & name) const [inline]
Get the first Property with name name of a given type T.
Parameters:
name The name of the property to search for.
T The data type of the property.
Returns:
The Property<T>* with this name, zero if it does not exist with the given type.
Definition at line 242 of file PropertyBag.hpp.
void RTT::PropertyBag::identify (base::PropertyIntrospection * pi) const
Identify the contents of this bag through introspection.
Deprecated:
DO NOT USE. Will be removed in 2.x release series.
Definition at line 187 of file PropertyBag.cpp.
Referenced by RTT::marsh::PropertyBagIntrospector::introspect().
void RTT::PropertyBag::identify (base::PropertyBagVisitor * pi) const
Identify the contents of this bag through introspection.
Deprecated:
DO NOT USE. Will be removed in 2.x release series.
Definition at line 197 of file PropertyBag.cpp.
void RTT::PropertyBag::list (Names & names) const
List the names of all properties.
Parameters:
names The container which will be used to store all available property names in.
Definition at line 151 of file PropertyBag.cpp.
Referenced by RTT::updateProperties().
std::vector< std::string > RTT::PropertyBag::list () const
List the names of all properties.
Returns:
A container of names.
Definition at line 161 of file PropertyBag.cpp.
PropertyBag& RTT::PropertyBag::operator<< (base::PropertyBase * item) [inline]
The 'add' operator.
Equivalent to add().
Parameters:
item The Property to add to this bag.
Definition at line 327 of file PropertyBag.hpp.
PropertyBag & RTT::PropertyBag::operator<<= (const PropertyBag & source)
The update operator.
It updates this bag so it contains all PropertyBases of another bag, removing own PropertyBases if duplicate names exist in the source bag.
Definition at line 251 of file PropertyBag.cpp.
References add(), find(), and getProperties().
void RTT::PropertyBag::remove (base::PropertyBase * p)
Remove a property from the container.
Analogous to removeProperty.
Parameters:
p Pointer to the property to be removed.
Definition at line 85 of file PropertyBag.cpp.
References removeProperty().
bool RTT::PropertyBag::removeProperty (base::PropertyBase * p)
Remove a property from the container.
Parameters:
p Pointer to the property to be removed.
Definition at line 122 of file PropertyBag.cpp.
References find().
Referenced by ownProperty(), remove(), and RTT::removeProperty().
The documentation for this class was generated from the following files:
rtt/PropertyBag.hpp
rtt/PropertyBag.cpp