Orocos Real-Time Toolkit: RTT::types::TypekitPlugin Class Reference
RTT::types::TypekitPlugin Class Reference
This interface defines how additional typekits are loaded into Orocos.
#include <rtt/types/TypekitPlugin.hpp>
Public Member Functions
virtual bool loadTypes ()=0
Implement this method to add types to the Orocos type system.
virtual bool loadOperators ()=0
Implement this method to load Scripting operators on types, such as '+', '*', ...
virtual bool loadConstructors ()=0
Implement this method to load Scripting constructors of types, such as in C++.
virtual bool loadGlobals ()
Implement this function to add global variables to the type system.
virtual std::string getName ()=0
Each plugin must have a unique name.
Detailed Description
This interface defines how additional typekits are loaded into Orocos.
A TypekitPlugin defines additional user data types for a Typekit.
Definition at line 51 of file TypekitPlugin.hpp.
Member Function Documentation
virtual std::string RTT::types::TypekitPlugin::getName () [pure virtual]
Each plugin must have a unique name.
This name is used globally in the process to identify this instance.
Implemented in RTT::types::RealTimeTypekitPlugin.
Referenced by RTT::types::TypekitRepository::Import().
virtual bool RTT::types::TypekitPlugin::loadConstructors () [pure virtual]
Implement this method to load Scripting constructors of types, such as in C++.
Default constructors (which take no arguments) need not to be added.
See also:
The TypeInfo class for adding a constructor to a type
The TypeBuilder class for the interface of a constructor.
The newConstructor utility function for creating a new constructor object.
The RealTimeTypekit for an implementation example.
Implemented in RTT::types::RealTimeTypekitPlugin.
Referenced by RTT::types::TypekitRepository::Import().
virtual bool RTT::types::TypekitPlugin::loadGlobals () [inline, virtual]
Implement this function to add global variables to the type system.
This is necessary to have something like enumeration values, without being force to look these up in a component.
Reimplemented in RTT::types::RealTimeTypekitPlugin.
Definition at line 99 of file TypekitPlugin.hpp.
Referenced by RTT::types::TypekitRepository::Import().
virtual bool RTT::types::TypekitPlugin::loadOperators () [pure virtual]
Implement this method to load Scripting operators on types, such as '+', '*', ...
See also:
The OperatorRepository for adding the Operators
The UnaryOp, BinaryOp and DotOp classes for the interface of an operation.
The newUnaryOperator, newBinaryOperator and newDotOperator functions for creating new operator objects.
The RealTimeTypekit for an implementation example.
Implemented in RTT::types::RealTimeTypekitPlugin.
Referenced by RTT::types::TypekitRepository::Import().
virtual bool RTT::types::TypekitPlugin::loadTypes () [pure virtual]
Implement this method to add types to the Orocos type system.
See also:
The TypeRepository for adding the types.
The TypeInfo class for the interface of a 'type'
The TemplateTypeInfo class for easy addition of new user types in scripting, XML,...
The TypeInfoName class for only 'name' addition of a user type
The TemplateIndexTypeInfo for adding container types.
The RealTimeTypekit for an implementation example.
Implemented in RTT::types::RealTimeTypekitPlugin.
Referenced by RTT::types::TypekitRepository::Import().
The documentation for this class was generated from the following file:
rtt/types/TypekitPlugin.hpp