Orocos Real-Time Toolkit: RTT::types::TypekitRepository Class Reference
RTT::types::TypekitRepository Class Reference
This class allows the RTT to be extended with additional typekits (TypekitPlugin), such as for kinematics or any library foreign to Orocos.
#include <rtt/types/TypekitRepository.hpp>
Static Public Member Functions
static void Import (TypekitPlugin *tkp)
Import a typekit plugin into the type system of this process.
static void Import (TransportPlugin *tr)
Import a transport plugin into the type system of this process.
static std::vector< std::string > getTypekits ()
Get the names of all imported typekits.
static std::vector< std::string > getTransports ()
Get the names of all imported transports.
static bool hasTypekit (const std::string &typekitname)
Check if a typekit with given name was already imported.
static bool hasTransport (const std::string &transportname)
Check if a transport with given name was already imported.
static void Release ()
Removes all Typekits and transports from memory.
Detailed Description
This class allows the RTT to be extended with additional typekits (TypekitPlugin), such as for kinematics or any library foreign to Orocos.
Definition at line 56 of file TypekitRepository.hpp.
Member Function Documentation
bool RTT::TypekitRepository::hasTransport (const std::string & transportname) [static]
Check if a transport with given name was already imported.
The name should have the form 'PROTOCOL://plugin', for example: "CORBA://rtt-types"
Definition at line 125 of file TypekitRepository.cpp.
void RTT::TypekitRepository::Import (TransportPlugin * tr) [static]
Import a transport plugin into the type system of this process.
One may try to load the same transport plugin multiple times from different places. Only the first import will succeed. Multiple imports will not be considered as an error, but will be silently freed.
Parameters:
tr A transport plugin that becomes owned by the TypekitRepository.
Definition at line 81 of file TypekitRepository.cpp.
References RTT::types::TransportPlugin::getName(), RTT::types::TransportPlugin::getTransportName(), and RTT::types::TransportPlugin::getTypekitName().
void RTT::TypekitRepository::Import (TypekitPlugin * tkp) [static]
Import a typekit plugin into the type system of this process.
One may try to load the same plugin multiple times from different places. Only the first import will succeed. Multiple imports will not be considered as an error, but will be silently freed.
Parameters:
tkp A typekit plugin that becomes owned by the TypekitRepository.
Definition at line 52 of file TypekitRepository.cpp.
References RTT::types::TypekitPlugin::getName(), RTT::types::TypekitPlugin::loadConstructors(), RTT::types::TypekitPlugin::loadGlobals(), RTT::types::TypekitPlugin::loadOperators(), and RTT::types::TypekitPlugin::loadTypes().
The documentation for this class was generated from the following files:
rtt/types/TypekitRepository.hpp
rtt/plugin/PluginLoader.cpp
rtt/types/TypekitRepository.cpp