Orocos Real-Time Toolkit: RTT::base::DataObject< T > Class Template Reference
RTT::base::DataObject< T > Class Template Reference
Data Storage and Buffering classes.
This object represents the default thread-safe data object implementation used by Orocos objects.
#include <rtt/base/DataObject.hpp>
Public Types
typedef T DataType
The type of the data.
typedef T value_t
typedef boost::shared_ptr
< DataObjectInterface< T > > shared_ptr
Used for shared_ptr management.
Public Member Functions
DataObject (const T &initial_value=T())
Create a data object for holding a user defined struct.
virtual DataType Get () const
Get a copy of the data.
virtual void Get (DataType &pull) const
Get a copy of the Data (non allocating).
virtual void Set (const DataType &push)
Set the data to a certain value (non blocking).
virtual void data_sample (const DataType &sample)
Provides a data sample to initialize this data object.
Public Attributes
const unsigned int MAX_THREADS
The maximum number of threads.
Detailed Description
template<class T>
class RTT::base::DataObject< T >
This object represents the default thread-safe data object implementation used by Orocos objects.
Definition at line 65 of file DataObject.hpp.
Member Function Documentation
template<class T > virtual void RTT::base::DataObjectLockFree< T >::data_sample (const DataType & sample) [inline, virtual, inherited]
Provides a data sample to initialize this data object.
As such enough storage space can be allocated before the actual writing begins.
Parameters:
sample
Implements RTT::base::DataObjectInterface< T >.
Definition at line 218 of file DataObjectLockFree.hpp.
Referenced by RTT::base::DataObjectLockFree< T >::DataObjectLockFree().
template<class T > virtual void RTT::base::DataObjectLockFree< T >::Get (DataType & pull) const [inline, virtual, inherited]
Get a copy of the Data (non allocating).
If pull has reserved enough memory to store the copy, no memory will be allocated.
Parameters:
pull A copy of the data.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 164 of file DataObjectLockFree.hpp.
References oro_atomic_dec(), and oro_atomic_inc().
template<class T > virtual DataType RTT::base::DataObjectLockFree< T >::Get () const [inline, virtual, inherited]
Get a copy of the data.
This method will allocate memory twice if data is not a value type. Use Get(DataType&) for the non-allocating version.
Returns:
A copy of the data.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 155 of file DataObjectLockFree.hpp.
References RTT::base::DataObjectLockFree< T >::Get().
Referenced by RTT::base::DataObjectLockFree< T >::Get().
template<class T > virtual void RTT::base::DataObjectLockFree< T >::Set (const DataType & push) [inline, virtual, inherited]
Set the data to a certain value (non blocking).
Parameters:
push The data which must be set.
This method can not be called concurrently (only one producer). With a minimum of 3 buffers, if the write_ptr+1 field is not occupied, it will remain so because the read_ptr is at write_ptr-1 (and can not increment the counter on write_ptr+1). Hence, no locking is needed.
Implements RTT::base::DataObjectInterface< T >.
Definition at line 191 of file DataObjectLockFree.hpp.
References oro_atomic_read().
Member Data Documentation
template<class T > const unsigned int RTT::base::DataObjectLockFree< T >::MAX_THREADS [inherited]
The maximum number of threads.
When used in data flow, this is always 2.
Definition at line 91 of file DataObjectLockFree.hpp.
The documentation for this class was generated from the following file:
rtt/base/DataObject.hpp