Orocos Real-Time Toolkit: RTT::mqueue::binary_data_oarchive Class Reference
RTT::mqueue::binary_data_oarchive Class Reference
This archive is capable of saving objects of serialization level 1 and 2 in a binary, non-portable format.
#include <rtt/transports/mqueue/binary_data_archive.hpp>
Classes
struct use_array_optimization
We provide an optimized load for all fundamental types typedef serialization::is_bitwise_serializable<mpl::_1> use_array_optimization;.
Public Types
typedef char Elem
typedef boost::mpl::bool_< false > is_loading
Saving Archive Concept::is_loading.
typedef boost::mpl::bool_< true > is_saving
Saving Archive Concept::is_saving.
Public Member Functions
binary_data_oarchive (std::ostream &os, bool do_save=true)
Constructor from a standard output stream.
binary_data_oarchive (std::streambuf &sb, bool do_save=true)
Constructor from a standard stream buffer.
unsigned int get_library_version ()
Saving Archive Concept::get_library_version()
template<class T >
const
boost::archive::detail::basic_pointer_iserializer * register_type (T *=NULL)
Saving Archive Concept::register_type<T>() and ::register_type(u)
void save_object (const void *x, const boost::archive::detail::basic_oserializer &bos)
Note: not in LoadArchive concept but required when we use archive::save !
template<class T >
binary_data_oarchive & operator<< (T const &t)
Saving Archive Concept::operator<<.
template<class T >
binary_data_oarchive & operator& (T const &t)
Saving Archive Concept::operator&.
void save_binary (const void *address, std::size_t count)
Saving Archive Concept::save_binary(u, count)
template<class T >
binary_data_oarchive & save_a_type (T const &t, boost::mpl::true_)
Specialisation for writing out primitive types.
template<class T >
binary_data_oarchive & save_a_type (T const &t, boost::mpl::false_)
Specialisation for writing out composite types (objects).
template<class ValueType >
void save_array (boost::serialization::array< ValueType > const &a, unsigned int)
The optimized save_array dispatches to save_binary.
int getArchiveSize ()
Helper method to say how much we wrote.
Detailed Description
This archive is capable of saving objects of serialization level 1 and 2 in a binary, non-portable format.
See also:
binary_data_iarchive
Definition at line 341 of file binary_data_archive.hpp.
Constructor & Destructor Documentation
RTT::mqueue::binary_data_oarchive::binary_data_oarchive (std::ostream & os, bool do_save = true) [inline]
Constructor from a standard output stream.
Parameters:
os The stream to serialize to
do_save Set to false to not actually write nor use the given ostream. After a save operation, only the counter for getArchiveSize() will have increased. Use this to know in advance how much space you will need.
Definition at line 365 of file binary_data_archive.hpp.
RTT::mqueue::binary_data_oarchive::binary_data_oarchive (std::streambuf & sb, bool do_save = true) [inline]
Constructor from a standard stream buffer.
Parameters:
os The buffer to serialize to.
do_save Set to false to not actually write nor use the given ostream. After a save operation, only the counter for getArchiveSize() will have increased. Use this to know in advance how much space you will need.
Definition at line 378 of file binary_data_archive.hpp.
Member Function Documentation
unsigned int RTT::mqueue::binary_data_oarchive::get_library_version () [inline]
Saving Archive Concept::get_library_version()
Returns:
This library's version.
Definition at line 387 of file binary_data_archive.hpp.
template<class T > binary_data_oarchive& RTT::mqueue::binary_data_oarchive::operator& (T const & t) [inline]
Saving Archive Concept::operator&.
Parameters:
t The type to save.
Returns:
*this
Definition at line 427 of file binary_data_archive.hpp.
References operator<<().
template<class T > binary_data_oarchive& RTT::mqueue::binary_data_oarchive::operator<< (T const & t) [inline]
Saving Archive Concept::operator<<.
Parameters:
t The type to save.
Returns:
*this
Definition at line 417 of file binary_data_archive.hpp.
References save_a_type().
Referenced by operator&().
template<class T > const boost::archive::detail::basic_pointer_iserializer* RTT::mqueue::binary_data_oarchive::register_type (T * = NULL) [inline]
Saving Archive Concept::register_type<T>() and ::register_type(u)
Parameters:
The data type to register in this archive.
Returns:
Definition at line 396 of file binary_data_archive.hpp.
template<class T > binary_data_oarchive& RTT::mqueue::binary_data_oarchive::save_a_type (T const & t, boost::mpl::false_) [inline]
Specialisation for writing out composite types (objects).
Parameters:
t a serializable class or struct.
Returns:
*this
Definition at line 474 of file binary_data_archive.hpp.
template<class T > binary_data_oarchive& RTT::mqueue::binary_data_oarchive::save_a_type (T const & t, boost::mpl::true_) [inline]
Specialisation for writing out primitive types.
Parameters:
t primitive data (bool, int,...)
Returns:
*this
Definition at line 463 of file binary_data_archive.hpp.
References save_binary().
Referenced by operator<<().
void RTT::mqueue::binary_data_oarchive::save_binary (const void * address, std::size_t count) [inline]
Saving Archive Concept::save_binary(u, count)
Parameters:
address The place where data is located in memory.
count The number of bytes to save.
Definition at line 436 of file binary_data_archive.hpp.
Referenced by save_a_type(), and save_array().
void RTT::mqueue::binary_data_oarchive::save_object (const void * x, const boost::archive::detail::basic_oserializer & bos) [inline]
Note: not in LoadArchive concept but required when we use archive::save !
Parameters:
x
bos
Definition at line 403 of file binary_data_archive.hpp.
The documentation for this class was generated from the following file:
rtt/transports/mqueue/binary_data_archive.hpp