Orocos Real-Time Toolkit: RTT::internal::ChannelDataElement< T > Class Template Reference
RTT::internal::ChannelDataElement< T > Class Template Reference
A connection element that stores a single data sample.
#include <rtt/internal/ChannelDataElement.hpp>
Public Types
typedef base::ChannelElement
< T >::param_t param_t
typedef base::ChannelElement
< T >::reference_t reference_t
typedef T value_t
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
Public Member Functions
ChannelDataElement (typename base::DataObjectInterface< T >::shared_ptr sample)
virtual bool write (param_t sample)
Update the data sample stored in this element.
virtual FlowStatus read (reference_t sample, bool copy_old_data)
Reads the last sample given to write()
virtual void clear ()
Resets the stored sample.
virtual bool data_sample (param_t sample)
Provides a data sample to initialize this connection.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
shared_ptr getInput ()
Returns the current input channel element.
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool inputReady ()
This is called by an input port when it is ready to receive data.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual PortInterface * getPort () const
Gets the port this channel element is connected to.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Detailed Description
template<typename T>
class RTT::internal::ChannelDataElement< T >
A connection element that stores a single data sample.
Definition at line 50 of file ChannelDataElement.hpp.
Member Function Documentation
template<typename T> virtual void RTT::internal::ChannelDataElement< T >::clear () [inline, virtual]
Resets the stored sample.
After clear() has been called, read() returns false
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 97 of file ChannelDataElement.hpp.
template<typename T> virtual bool RTT::internal::ChannelDataElement< T >::data_sample (param_t sample) [inline, virtual]
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns:
false if an error occured that requires the channel to be invalidated.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 104 of file ChannelDataElement.hpp.
virtual void RTT::base::ChannelElementBase::disconnect (bool forward) [virtual, inherited]
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, RTT::internal::ConnOutputEndpoint< T >, and RTT::corba::RemoteChannelElement< T >.
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getInput () [inline, inherited]
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to setOutput().
Returns:
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 68 of file ChannelElement.hpp.
Referenced by RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () [inherited]
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns:
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 96 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () [inherited]
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns:
getOutput() ? getOutput()->getInputEndPoint() : this
Definition at line 101 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
virtual PortInterface* RTT::base::ChannelElementBase::getPort () const [virtual, inherited]
Gets the port this channel element is connected to.
Returns:
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, and RTT::internal::ConnOutputEndpoint< T >.
virtual bool RTT::base::ChannelElementBase::inputReady () [virtual, inherited]
This is called by an input port when it is ready to receive data.
Each channel element has the responsibility to pass this notification on to the next, in the direction of the output.
Returns:
false if a fatal connection failure was encountered and the channel needs to be destroyed.
Reimplemented in RTT::internal::ConnInputEndpoint< T >, RTT::internal::ConnOutputEndpoint< T >, RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
template<typename T> virtual FlowStatus RTT::internal::ChannelDataElement< T >::read (reference_t sample, bool copy_old_data) [inline, virtual]
Reads the last sample given to write()
Returns:
false if no sample has ever been written, true otherwise
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 76 of file ChannelDataElement.hpp.
void RTT::base::ChannelElementBase::removeInput () [inherited]
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output) [inherited]
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters:
output the next element in chain.
Definition at line 68 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), and RTT::internal::ConnFactory::buildChannelInput().
virtual bool RTT::base::ChannelElementBase::signal () [virtual, inherited]
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns:
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::internal::ConnOutputEndpoint< T >, RTT::corba::RemoteChannelElement< T >, and RTT::mqueue::MQChannelElement< T >.
Referenced by RTT::internal::ChannelDataElement< T >::write(), and RTT::internal::ChannelBufferElement< T >::write().
template<typename T> virtual bool RTT::internal::ChannelDataElement< T >::write (param_t sample) [inline, virtual]
Update the data sample stored in this element.
It always returns true.
Reimplemented from RTT::base::ChannelElement< T >.
Definition at line 64 of file ChannelDataElement.hpp.
References RTT::base::ChannelElementBase::signal().
The documentation for this class was generated from the following file:
rtt/internal/ChannelDataElement.hpp