Orocos Real-Time Toolkit: RTT::internal::ConnOutputEndpoint< T > Class Template Reference
RTT::internal::ConnOutputEndpoint< T > Class Template Reference
This is a channel element that represents the output endpoint of a connection, i.e.
#include <rtt/internal/ConnOutputEndPoint.hpp>
Public Types
typedef T value_t
typedef boost::intrusive_ptr
< ChannelElement< T > > shared_ptr
typedef boost::call_traits< T >
::param_type param_t
typedef boost::call_traits< T >
::reference reference_t
Public Member Functions
ConnOutputEndpoint (InputPort< T > *port, ConnID *output_id)
Creates the connection end that represents the output and attach it to the input.
bool inputReady ()
Called by the connection factory to check that the connection is properly set up.
virtual bool write (typename base::ChannelElement< T >::param_t sample)
Writes a new sample on this connection This should never be called, as all connections are supposed to have a data storage element.
virtual void disconnect (bool forward)
Performs a disconnection of this channel's endpoints.
virtual bool signal ()
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
virtual bool data_sample (typename base::ChannelElement< T >::param_t sample)
virtual base::PortInterface * getPort () const
Gets the port this channel element is connected to.
shared_ptr getOutput ()
Returns the next channel element in the channel's propagation direction.
shared_ptr getInput ()
Returns the current input channel element.
virtual bool data_sample (param_t sample)
Provides a data sample to initialize this connection.
virtual bool write (param_t sample)
Writes a new sample on this connection.
virtual FlowStatus read (reference_t sample, bool copy_old_data)
Reads a sample from the connection.
void removeInput ()
Removes the input channel (if any).
ChannelElementBase::shared_ptr getInputEndPoint ()
Returns the first input channel element of this connection.
ChannelElementBase::shared_ptr getOutputEndPoint ()
Returns the last output channel element of this connection.
void setOutput (shared_ptr output)
Sets the output of this channel element to output and sets the input of output to this.
virtual void clear ()
Clears any data stored by the channel.
Protected Member Functions
void ref ()
Increases the reference count.
void deref ()
Decreases the reference count, and deletes the object if it is zero.
Detailed Description
template<typename T>
class RTT::internal::ConnOutputEndpoint< T >
This is a channel element that represents the output endpoint of a connection, i.e.
the part that is connected to the InputPort. In the RTT, connections are always created from input towards output. So this class is typically first created of the channel element chain and attached to the input port. Then we build further towards the outputport. Imagine a spider attaching a thread at one wall and moving along to the other side of the wall.
Definition at line 57 of file ConnOutputEndPoint.hpp.
Constructor & Destructor Documentation
template<typename T> RTT::internal::ConnOutputEndpoint< T >::ConnOutputEndpoint (InputPort< T > * port, ConnID * output_id) [inline]
Creates the connection end that represents the output and attach it to the input.
Parameters:
port The start point.
output_id Each connection must be identified by an ID that represents the other end. This id is passed to the input port port.
Returns:
Definition at line 70 of file ConnOutputEndPoint.hpp.
Member Function Documentation
virtual void RTT::base::ChannelElementBase::clear () [virtual, inherited]
Clears any data stored by the channel.
It means that ChannelElement::read() will return false afterwards (provided that no new data has been written on the meantime of course)
By default, the channel element forwards the calls to its input
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
template<typename T> virtual bool RTT::base::ChannelElement< T >::data_sample (param_t sample) [inline, virtual, inherited]
Provides a data sample to initialize this connection.
This is used before the first write() in order to inform this connection of the size of the data. As such enough storage space can be allocated before the actual writing begins.
Returns:
false if an error occured that requires the channel to be invalidated.
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 82 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::data_sample(), and RTT::base::ChannelElement< T >::getOutput().
Referenced by RTT::base::ChannelElement< T >::data_sample(), and RTT::mqueue::MQChannelElement< T >::inputReady().
template<typename T> virtual void RTT::internal::ConnOutputEndpoint< T >::disconnect (bool forward) [inline, virtual]
Performs a disconnection of this channel's endpoints.
If forward is true, then the disconnection is initiated by the input endpoint. Otherwise, it has been initiated by the output endpoint.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 102 of file ConnOutputEndPoint.hpp.
References RTT::base::InputPortInterface::removeConnection().
template<typename T> shared_ptr RTT::base::ChannelElement< T >::getInput () [inline, inherited]
Returns the current input channel element.
This will only return a valid channel element if another element has received this object as an argument to setOutput().
Returns:
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 68 of file ChannelElement.hpp.
Referenced by RTT::corba::RemoteChannelElement< T >::inputReady(), RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
ChannelElementBase::shared_ptr ChannelElementBase::getInputEndPoint () [inherited]
Returns the first input channel element of this connection.
Will return the channel element the furthest away from the input port, or this if none.
Returns:
getInput() ? getInput()->getInputEndPoint() : this
Definition at line 96 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getInput().
ChannelElementBase::shared_ptr ChannelElementBase::getOutputEndPoint () [inherited]
Returns the last output channel element of this connection.
Will return the channel element the furthest away from the output port, or this if none.
Returns:
getOutput() ? getOutput()->getInputEndPoint() : this
Definition at line 101 of file ChannelInterface.cpp.
References RTT::base::ChannelElementBase::getOutput().
template<typename T> virtual base::PortInterface* RTT::internal::ConnOutputEndpoint< T >::getPort () const [inline, virtual]
Gets the port this channel element is connected to.
Returns:
null if no port is connected to this element, the port (or a proxy representing the port) otherwise.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 130 of file ConnOutputEndPoint.hpp.
template<typename T> bool RTT::internal::ConnOutputEndpoint< T >::inputReady () [inline, virtual]
Called by the connection factory to check that the connection is properly set up.
It is called when the channel is complete, so we can register ourselves on the port side now
Before that, the channel might not be complete and therefore having the input port read on it would lead to crashes
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 87 of file ConnOutputEndPoint.hpp.
template<typename T> virtual FlowStatus RTT::base::ChannelElement< T >::read (reference_t sample, bool copy_old_data) [inline, virtual, inherited]
Reads a sample from the connection.
sample is a reference which will get updated if a sample is available. The method returns true if a sample was available, and false otherwise. If false is returned, then sample is not modified by the method
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 108 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::getInput(), and RTT::base::ChannelElement< T >::read().
Referenced by RTT::base::ChannelElement< T >::read(), and RTT::mqueue::MQChannelElement< T >::signal().
void RTT::base::ChannelElementBase::removeInput () [inherited]
Removes the input channel (if any).
This call may delete channels from memory.
void ChannelElementBase::setOutput (shared_ptr output) [inherited]
Sets the output of this channel element to output and sets the input of output to this.
This implies that this channel element becomes the input of output. There is no setInput function since this function does both setting input and output of this and output.
Parameters:
output the next element in chain.
Definition at line 68 of file ChannelInterface.cpp.
Referenced by RTT::internal::ConnFactory::buildBufferedChannelInput(), RTT::internal::ConnFactory::buildBufferedChannelOutput(), and RTT::internal::ConnFactory::buildChannelInput().
template<typename T> virtual bool RTT::internal::ConnOutputEndpoint< T >::signal () [inline, virtual]
Signals that there is new data available on this channel By default, the channel element forwards the call to its output.
Returns:
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented from RTT::base::ChannelElementBase.
Definition at line 116 of file ConnOutputEndPoint.hpp.
References RTT::base::InputPortInterface::signal().
template<typename T> virtual bool RTT::base::ChannelElement< T >::write (param_t sample) [inline, virtual, inherited]
Writes a new sample on this connection.
sample is the sample to write.
Returns:
false if an error occured that requires the channel to be invalidated. In no ways it indicates that the sample has been received by the other side of the channel.
Reimplemented in RTT::internal::ChannelBufferElement< T >, and RTT::internal::ChannelDataElement< T >.
Definition at line 95 of file ChannelElement.hpp.
References RTT::base::ChannelElement< T >::getOutput(), and RTT::base::ChannelElement< T >::write().
Referenced by RTT::mqueue::MQChannelElement< T >::signal(), and RTT::base::ChannelElement< T >::write().
The documentation for this class was generated from the following file:
rtt/internal/ConnOutputEndPoint.hpp