Orocos Real-Time Toolkit: RTT::base::DataSourceBase Class Reference
RTT::base::DataSourceBase Class Reference
The base class for all internal data representations.
#include <rtt/base/DataSourceBase.hpp>
Public Types
typedef boost::intrusive_ptr
< DataSourceBase > shared_ptr
Use this type to store a pointer to a DataSourceBase.
typedef boost::intrusive_ptr
< const DataSourceBase > const_ptr
Use this type to store a const pointer to a DataSourceBase.
Public Member Functions
void ref () const
Increase the reference count by one.
void deref () const
Decrease the reference count by one and delete this on zero.
virtual void reset ()
Reset the data to initial values.
virtual bool evaluate () const =0
Force an evaluation of the DataSourceBase.
virtual bool isAssignable () const
Returns true if this object can be cast to an AssignableDataSource.
virtual void updated ()
In case the internal::DataSource returns a 'reference' type, call this method to notify it that the data was updated in the course of an invocation of get().
virtual bool update (DataSourceBase *other)
Update the value of this internal::DataSource with the value of an other DataSource.
virtual ActionInterface * updateAction (DataSourceBase *other)
Generate a ActionInterface object which will update this internal::DataSource with the value of another internal::DataSource when execute()'ed.
virtual shared_ptr getMember (const std::string &member_name)
Get a (const) reference data source to a member of the structure of this data source.
virtual shared_ptr getMember (DataSourceBase::shared_ptr member_id, DataSourceBase::shared_ptr offset)
Same as above, but with run-time lookup of the member to use.
virtual std::vector< std::string > getMemberNames () const
Returns the names of all members of the structure contained in this data source, or an empty list if none.
virtual shared_ptr getParent ()
Returns the top level data source that contains the full data structure this data source refers to.
virtual DataSourceBase * clone () const =0
Return a shallow clone of this DataSource.
virtual DataSourceBase * copy (std::map< const DataSourceBase *, DataSourceBase * > &alreadyCloned) const =0
Create a deep copy of this internal::DataSource, unless it is already cloned.
virtual std::string getType () const =0
Return useful type info in a human readable format.
virtual const types::TypeInfo * getTypeInfo () const =0
Return the Orocos type info object.
virtual std::string getTypeName () const =0
Return the Orocos type name, without const, pointer or reference qualifiers.
std::ostream & write (std::ostream &os)
Stream the contents of this object.
std::string toString ()
Get the contents of this object as a string.
virtual void * getRawPointer ()
Returns a pointer to the sample contained in this data source, if there is any, and if it is an lvalue.
virtual void const * getRawConstPointer ()
Returns a const pointer to the sample contained in this data source, if there is any.
Static Public Member Functions
static shared_ptr stack_shared_ptr (DataSourceBase *dsb)
Returns a shared ptr to a DataSourceBase living on the stack.
static const_ptr stack_const_ptr (const DataSourceBase *dsb)
Returns a const shared_ptr to a DataSourceBase living on the stack.
Protected Member Functions
virtual ~DataSourceBase ()
the destructor is private.
Protected Attributes
os::AtomicInt refcount
We keep the refcount ourselves.
Detailed Description
The base class for all internal data representations.
The internal::DataSource is an object containing Data of any type. It's interface is designed for dynamic build-up and destruction of these objects and allowing Commands, Properties etc to use them as 'storage' devices which have the dual copy() /clone() semantics (which is heavily used by the Orocos type and scripting Infrastructure).
internal::DataSource's are reference counted and must be allocated on the heap. Use DataSourceBase::shared_ptr or internal::DataSource<T>::shared_ptr to deal with cleanup of allocated DataSources. You are not allowed to delete a DataSource. If you must have the pointer of a internal::DataSource, use the .get() method of the shared_ptr class.
Once a newly created internal::DataSource is assigned to a shared_ptr, it will be deleted when that pointer goes out of scope and is not shared by other shared_ptr objects.
See also:
internal::DataSource
Definition at line 76 of file DataSourceBase.hpp.
Constructor & Destructor Documentation
RTT::DataSourceBase::~DataSourceBase () [protected, virtual]
the destructor is private.
You are not allowed to delete this class RTT_API yourself, use a shared pointer !
Definition at line 83 of file DataSource.cpp.
Member Function Documentation
virtual DataSourceBase* RTT::base::DataSourceBase::clone () const [pure virtual]
Return a shallow clone of this DataSource.
This method returns a duplicate of this instance which re-uses the DataSources this internal::DataSource holds reference to. The clone() function is thus a non-deep copy.
Implemented in RTT::internal::ArrayPartDataSource< T >, RTT::internal::DataObjectDataSource< T >, RTT::internal::DataSource< T >, RTT::internal::AssignableDataSource< T >, RTT::internal::DataSourceCommand, RTT::internal::ValueDataSource< T >, RTT::internal::ConstantDataSource< T >, RTT::internal::ConstReferenceDataSource< T >, RTT::internal::ReferenceDataSource< T >, RTT::internal::AliasDataSource< T >, RTT::internal::ArrayDataSource< T >, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::BinaryDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::NArityDataSource< function >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::FusedMCollectDataSource< Signature >, RTT::internal::InputPortSource< T >, RTT::internal::OffsetDataSource, RTT::internal::OffsetPartDataSource< T >, RTT::internal::PartDataSource< T >, RTT::scripting::DataSourceCondition, RTT::scripting::DataSourceTime, RTT::corba::AnyDataSource, RTT::corba::DataSourceProxy< T >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::DataSource< ProgramInterfacePtr >, RTT::internal::DataSource< DataSourceType >, RTT::internal::DataSource< SendStatus >, RTT::internal::DataSource< double >, RTT::internal::DataSource< offset_type >, RTT::internal::DataSource< SendHandle< Signature > >, RTT::internal::DataSource< A >, RTT::internal::DataSource< S >, RTT::internal::DataSource< CORBA::Any_var >, RTT::internal::DataSource< unsigned int >, RTT::internal::DataSource< types::carray< T > >, RTT::internal::DataSource< remove_cr< function::result_type >::type >, RTT::internal::DataSource< os::TimeService::Seconds >, RTT::internal::DataSource< arg_t >, RTT::internal::DataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::DataSource< second_arg_t >, RTT::internal::DataSource< ds_type >, RTT::internal::DataSource< value_t >, RTT::internal::DataSource< ProgramInterface * >, RTT::internal::DataSource< bool >, RTT::internal::DataSource< StateMachinePtr >, RTT::internal::DataSource< boost::shared_ptr< ObjT > >, RTT::internal::DataSource< first_arg_t >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, RTT::internal::AssignableDataSource< StateMachinePtr >, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::LateReferenceDataSource< ds_type >, and RTT::internal::LateConstReferenceDataSource< A >.
virtual DataSourceBase* RTT::base::DataSourceBase::copy (std::map< const DataSourceBase *, DataSourceBase * > & alreadyCloned) const [pure virtual]
Create a deep copy of this internal::DataSource, unless it is already cloned.
Places the association (parent, clone) in alreadyCloned. If the internal::DataSource is non-copyable (for example it represents the Property of a Task), this may be returned.
Implemented in RTT::internal::ArrayPartDataSource< T >, RTT::internal::DataObjectDataSource< T >, RTT::internal::DataSource< T >, RTT::internal::AssignableDataSource< T >, RTT::internal::DataSourceCommand, RTT::internal::ValueDataSource< T >, RTT::internal::ConstantDataSource< T >, RTT::internal::ConstReferenceDataSource< T >, RTT::internal::ReferenceDataSource< T >, RTT::internal::AliasDataSource< T >, RTT::internal::ArrayDataSource< T >, RTT::internal::LateReferenceDataSource< T >, RTT::internal::LateConstReferenceDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::BinaryDataSource< function >, RTT::internal::UnaryDataSource< function >, RTT::internal::NArityDataSource< function >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::FusedMSendDataSource< Signature >, RTT::internal::FusedMCollectDataSource< Signature >, RTT::internal::InputPortSource< T >, RTT::internal::OffsetDataSource, RTT::internal::OffsetPartDataSource< T >, RTT::internal::PartDataSource< T >, RTT::scripting::DataSourceCondition, RTT::scripting::DataSourceTime, RTT::corba::AnyDataSource, RTT::corba::DataSourceProxy< T >, RTT::corba::ValueDataSourceProxy< T >, RTT::internal::DataSource< ProgramInterfacePtr >, RTT::internal::DataSource< DataSourceType >, RTT::internal::DataSource< SendStatus >, RTT::internal::DataSource< double >, RTT::internal::DataSource< offset_type >, RTT::internal::DataSource< SendHandle< Signature > >, RTT::internal::DataSource< A >, RTT::internal::DataSource< S >, RTT::internal::DataSource< CORBA::Any_var >, RTT::internal::DataSource< unsigned int >, RTT::internal::DataSource< types::carray< T > >, RTT::internal::DataSource< remove_cr< function::result_type >::type >, RTT::internal::DataSource< os::TimeService::Seconds >, RTT::internal::DataSource< arg_t >, RTT::internal::DataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::DataSource< second_arg_t >, RTT::internal::DataSource< ds_type >, RTT::internal::DataSource< value_t >, RTT::internal::DataSource< ProgramInterface * >, RTT::internal::DataSource< bool >, RTT::internal::DataSource< StateMachinePtr >, RTT::internal::DataSource< boost::shared_ptr< ObjT > >, RTT::internal::DataSource< first_arg_t >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, RTT::internal::AssignableDataSource< StateMachinePtr >, RTT::internal::ValueDataSource< ProgramInterfacePtr >, RTT::internal::ValueDataSource< ds_type >, RTT::internal::ValueDataSource< StateMachinePtr >, RTT::internal::ReferenceDataSource< ds_type >, RTT::internal::LateReferenceDataSource< ds_type >, and RTT::internal::LateConstReferenceDataSource< A >.
virtual bool RTT::base::DataSourceBase::evaluate () const [pure virtual]
Force an evaluation of the DataSourceBase.
Returns:
true on successful evaluation.
Implemented in RTT::internal::DataObjectDataSource< T >, RTT::internal::DataSource< T >, RTT::internal::AliasDataSource< T >, RTT::internal::ActionAliasDataSource< T >, RTT::internal::ActionAliasAssignableDataSource< T >, RTT::internal::FusedFunctorDataSource< Signature, Enable >, RTT::internal::FusedMCallDataSource< Signature >, RTT::internal::InputPortSource< T >, RTT::internal::DataSource< ProgramInterfacePtr >, RTT::internal::DataSource< DataSourceType >, RTT::internal::DataSource< SendStatus >, RTT::internal::DataSource< double >, RTT::internal::DataSource< offset_type >, RTT::internal::DataSource< SendHandle< Signature > >, RTT::internal::DataSource< A >, RTT::internal::DataSource< S >, RTT::internal::DataSource< CORBA::Any_var >, RTT::internal::DataSource< unsigned int >, RTT::internal::DataSource< types::carray< T > >, RTT::internal::DataSource< remove_cr< function::result_type >::type >, RTT::internal::DataSource< os::TimeService::Seconds >, RTT::internal::DataSource< arg_t >, RTT::internal::DataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::DataSource< second_arg_t >, RTT::internal::DataSource< ds_type >, RTT::internal::DataSource< value_t >, RTT::internal::DataSource< ProgramInterface * >, RTT::internal::DataSource< bool >, RTT::internal::DataSource< StateMachinePtr >, RTT::internal::DataSource< boost::shared_ptr< ObjT > >, and RTT::internal::DataSource< first_arg_t >.
DataSourceBase::shared_ptr RTT::DataSourceBase::getMember (const std::string & member_name) [virtual]
Get a (const) reference data source to a member of the structure of this data source.
You must call getMember() in turn on the returned member to access sub-members.
Parameters:
member_name The name of the member to get access to.
Returns:
null if the member does not exist, this if member_name.empty(), and a reference data source to the member otherwise.
Definition at line 124 of file DataSource.cpp.
References RTT::types::TypeInfo::getMember(), and getTypeInfo().
DataSourceBase::shared_ptr RTT::DataSourceBase::getMember (DataSourceBase::shared_ptr member_id, DataSourceBase::shared_ptr offset) [virtual]
Same as above, but with run-time lookup of the member to use.
Also takes an optional offset argument which can be used to offset the member in memory. This is necessary when using sequences of sequences. DataSources which are a sequence/offset member themselves must override this function to let the returned member take the offset into account.
Definition at line 130 of file DataSource.cpp.
References RTT::types::TypeInfo::getMember(), and getTypeInfo().
vector< string > RTT::DataSourceBase::getMemberNames () const [virtual]
Returns the names of all members of the structure contained in this data source, or an empty list if none.
If this data source is a sequence, it will not return the allowed index numbers.
Definition at line 134 of file DataSource.cpp.
References RTT::types::TypeInfo::getMemberNames(), and getTypeInfo().
DataSourceBase::shared_ptr RTT::DataSourceBase::getParent () [virtual]
Returns the top level data source that contains the full data structure this data source refers to.
Defaults to returning this.
Reimplemented in RTT::internal::OffsetPartDataSource< T >.
Definition at line 138 of file DataSource.cpp.
void const * RTT::DataSourceBase::getRawConstPointer () [virtual]
Returns a const pointer to the sample contained in this data source, if there is any.
Returns 0 otherwise
Reimplemented in RTT::internal::DataSource< T >, RTT::internal::DataSource< ProgramInterfacePtr >, RTT::internal::DataSource< DataSourceType >, RTT::internal::DataSource< SendStatus >, RTT::internal::DataSource< double >, RTT::internal::DataSource< offset_type >, RTT::internal::DataSource< SendHandle< Signature > >, RTT::internal::DataSource< A >, RTT::internal::DataSource< S >, RTT::internal::DataSource< CORBA::Any_var >, RTT::internal::DataSource< unsigned int >, RTT::internal::DataSource< types::carray< T > >, RTT::internal::DataSource< remove_cr< function::result_type >::type >, RTT::internal::DataSource< os::TimeService::Seconds >, RTT::internal::DataSource< arg_t >, RTT::internal::DataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::DataSource< second_arg_t >, RTT::internal::DataSource< ds_type >, RTT::internal::DataSource< value_t >, RTT::internal::DataSource< ProgramInterface * >, RTT::internal::DataSource< bool >, RTT::internal::DataSource< StateMachinePtr >, RTT::internal::DataSource< boost::shared_ptr< ObjT > >, RTT::internal::DataSource< first_arg_t >, and RTT::internal::DataSource< T >.
Definition at line 117 of file DataSource.cpp.
void * RTT::DataSourceBase::getRawPointer () [virtual]
Returns a pointer to the sample contained in this data source, if there is any, and if it is an lvalue.
Returns 0 otherwise
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, and RTT::internal::AssignableDataSource< StateMachinePtr >.
Definition at line 115 of file DataSource.cpp.
bool RTT::DataSourceBase::isAssignable () const [virtual]
Returns true if this object can be cast to an AssignableDataSource.
When this method returns true, all update functions below will return as well when valid input is given.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, and RTT::internal::AssignableDataSource< StateMachinePtr >.
Definition at line 104 of file DataSource.cpp.
DataSourceBase::const_ptr RTT::DataSourceBase::stack_const_ptr (const DataSourceBase * dsb) [static]
Returns a const shared_ptr to a DataSourceBase living on the stack.
Make sure that the const_ptr does not outlive the stacked element.
Definition at line 74 of file DataSource.cpp.
References ref().
DataSourceBase::shared_ptr RTT::DataSourceBase::stack_shared_ptr (DataSourceBase * dsb) [static]
Returns a shared ptr to a DataSourceBase living on the stack.
Make sure that the shared_ptr does not outlive the stacked element.
Definition at line 69 of file DataSource.cpp.
References ref().
std::string RTT::DataSourceBase::toString ()
Get the contents of this object as a string.
See also:
types::TypeInfo
Definition at line 98 of file DataSource.cpp.
bool RTT::DataSourceBase::update (DataSourceBase * other) [virtual]
Update the value of this internal::DataSource with the value of an other DataSource.
Update does a full update of the value, adding extra information if necessary.
Precondition:
this->isAssignable() == true
Returns:
false if the DataSources are of different type OR if the contents of this internal::DataSource can not be updated.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, and RTT::internal::AssignableDataSource< StateMachinePtr >.
Definition at line 108 of file DataSource.cpp.
ActionInterface * RTT::DataSourceBase::updateAction (DataSourceBase * other) [virtual]
Generate a ActionInterface object which will update this internal::DataSource with the value of another internal::DataSource when execute()'ed.
Precondition:
this->isAssignable() == true
Returns:
zero if the internal::DataSource types do not match OR if the contents of this internal::DataSource can not be updated.
Reimplemented in RTT::internal::AssignableDataSource< T >, RTT::internal::AssignableDataSource< ProgramInterfacePtr >, RTT::internal::AssignableDataSource< DataSourceType >, RTT::internal::AssignableDataSource< types::carray< T > >, RTT::internal::AssignableDataSource< remove_cr< boost::function_traits< Signature >::result_type >::type >, RTT::internal::AssignableDataSource< ds_type >, RTT::internal::AssignableDataSource< value_t >, RTT::internal::AssignableDataSource< ProgramInterface * >, RTT::internal::AssignableDataSource< bool >, and RTT::internal::AssignableDataSource< StateMachinePtr >.
Definition at line 120 of file DataSource.cpp.
std::ostream & RTT::DataSourceBase::write (std::ostream & os)
Stream the contents of this object.
See also:
types::TypeInfo
Definition at line 91 of file DataSource.cpp.
Member Data Documentation
os::AtomicInt RTT::base::DataSourceBase::refcount [mutable, protected]
We keep the refcount ourselves.
We aren't using boost::shared_ptr, because boost::intrusive_ptr is better, exactly because it can be used with refcounts that are stored in the class itself. Advantages are that the shared_ptr's for derived classes use the same refcount, which is of course very much desired, and that refcounting happens in an efficient way, which is also nice :)
Definition at line 88 of file DataSourceBase.hpp.
Referenced by deref(), and ref().
The documentation for this class was generated from the following files:
rtt/base/DataSourceBase.hpp
rtt/internal/DataSource.cpp