Orocos Real-Time Toolkit: RTT::scripting::CommandComposite Class Reference
RTT::scripting::CommandComposite Class Reference
Based on the software pattern 'composite', this class RTT_SCRIPTING_API allows composing command objects into one command object.
#include <rtt/scripting/CommandComposite.hpp>
Public Types
typedef boost::shared_ptr
< ActionInterface > shared_ptr
Use this type for shared pointer storage of an ActionInterface object.
Public Member Functions
CommandComposite (std::vector< base::ActionInterface * > cv)
CommandComposite (const CommandComposite &orig)
Copy-Construct a clone() of all commands.
virtual bool execute ()
Execute the functionality of all commands.
void readArguments ()
This is invoked some time before execute() at a time when the action may read its function arguments.
bool valid () const
Inspect if this action was executed and valid.
virtual void add (base::ActionInterface *com)
add a command to the vect
virtual base::ActionInterface * clone () const
The Clone Software Pattern.
virtual base::ActionInterface * copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > &alreadyCloned) const
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
virtual void reset ()
Reset this action.
Detailed Description
Based on the software pattern 'composite', this class RTT_SCRIPTING_API allows composing command objects into one command object.
Definition at line 50 of file CommandComposite.hpp.
Member Function Documentation
virtual void RTT::scripting::CommandComposite::add (base::ActionInterface * com) [inline, virtual]
add a command to the vect
Definition at line 106 of file CommandComposite.hpp.
Referenced by RTT::scripting::FunctionGraphBuilder::appendFunction(), copy(), and RTT::scripting::FunctionFactory::produce().
virtual base::ActionInterface* RTT::scripting::CommandComposite::copy (std::map< const base::DataSourceBase *, base::DataSourceBase * > & alreadyCloned) const [inline, virtual]
When copying an Orocos program, we want identical internal::DataSource's to be mapped to identical DataSources, in order for the program to work correctly.
This is different from the clone function, where we simply want a new Action that can replace the old one directly.
This function takes a map that maps the old internal::DataSource's onto their new replacements. This way, it is possible to check before cloning a internal::DataSource, whether it has already been copied, and if so, reuse the existing copy.
To keep old source working, the standard implementation of this function simply calls the clone function. If your ActionInterface uses a internal::DataSource, it is important that you reimplement this function correctly though.
Reimplemented from RTT::base::ActionInterface.
Definition at line 115 of file CommandComposite.hpp.
References add().
virtual bool RTT::scripting::CommandComposite::execute () [inline, virtual]
Execute the functionality of all commands.
Commands will be executed in the order they have been added
Implements RTT::base::ActionInterface.
Definition at line 81 of file CommandComposite.hpp.
void RTT::ActionInterface::reset () [virtual, inherited]
Reset this action.
Must be used after execute() failed.
Reimplemented in RTT::scripting::CallFunction, RTT::scripting::CommandCounter, RTT::scripting::CommandDataSource, RTT::scripting::CommandDataSourceBool, RTT::scripting::TryCommand, and RTT::scripting::EvalCommand.
Definition at line 50 of file ActionInterface.cpp.
Referenced by RTT::scripting::StateMachine::activate(), RTT::internal::ActionAliasAssignableDataSource< T >::evaluate(), RTT::internal::ActionAliasDataSource< T >::evaluate(), RTT::internal::ActionAliasAssignableDataSource< T >::get(), RTT::internal::ActionAliasDataSource< T >::get(), RTT::scripting::TryCommand::reset(), RTT::internal::DataSourceCommand::reset(), and RTT::scripting::VertexNode::startExecution().
bool RTT::scripting::CommandComposite::valid () const [inline, virtual]
Inspect if this action was executed and valid.
This method may not be called before execute(). The default implementation returns always true, i.e. after execute(), it was executed. Override this method if it has more complex state semantics.
Reimplemented from RTT::base::ActionInterface.
Definition at line 94 of file CommandComposite.hpp.
The documentation for this class was generated from the following file:
rtt/scripting/CommandComposite.hpp