Orocos Real-Time Toolkit: Recursive Property Bag Operations.
Recursive Property Bag Operations.
Property Interface
These functions operate recursively on the contents of bags, possibly modifying, deleting or creating new Property objects in the bag or in one of its sub-bags.
Functions
std::ostream & RTT::operator<< (std::ostream &os, const PropertyBag &bag)
Recursively prints out the contents of this bag.
std::istream & RTT::operator>> (std::istream &is, PropertyBag &bag)
Not implemented.
Detailed Description
These functions operate recursively on the contents of bags, possibly modifying, deleting or creating new Property objects in the bag or in one of its sub-bags.
Function Documentation
RTT_API std::ostream & RTT::operator<< (std::ostream & os, const PropertyBag & bag)
Recursively prints out the contents of this bag.
Parameters:
os A Std stream to print to
bag The bag to print.
Returns:
os
Definition at line 295 of file PropertyBag.cpp.
References RTT::os::endl(), RTT::PropertyBag::getItem(), RTT::base::PropertyBase::getName(), RTT::base::operator<<(), and RTT::PropertyBag::size().
RTT_API std::istream & RTT::operator>> (std::istream & is, PropertyBag & bag)
Not implemented.
Parameters:
is unused
bag unused
Returns:
is
Definition at line 306 of file PropertyBag.cpp.
References RTT::extras::operator>>().