/*
* generated by Xtext
*/
package org.best.of.robotics.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.best.of.robotics.services.SmachDSLGrammarAccess;

public class SmachDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private SmachDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.best.of.robotics.ui.contentassist.antlr.internal.InternalSmachDSLParser createParser() {
		org.best.of.robotics.ui.contentassist.antlr.internal.InternalSmachDSLParser result = new org.best.of.robotics.ui.contentassist.antlr.internal.InternalSmachDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getOUTCOMEAccess().getAlternatives(), "rule__OUTCOME__Alternatives");
					put(grammarAccess.getStateMachineAccess().getGroup(), "rule__StateMachine__Group__0");
					put(grammarAccess.getActionClientAccess().getGroup(), "rule__ActionClient__Group__0");
					put(grammarAccess.getServiceClientAccess().getGroup(), "rule__ServiceClient__Group__0");
					put(grammarAccess.getActionStateAccess().getGroup(), "rule__ActionState__Group__0");
					put(grammarAccess.getActionStateAccess().getGroup_6(), "rule__ActionState__Group_6__0");
					put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
					put(grammarAccess.getPrimitivePackageAccess().getStatemachinesAssignment(), "rule__PrimitivePackage__StatemachinesAssignment");
					put(grammarAccess.getTestAccess().getRosAssignment(), "rule__Test__RosAssignment");
					put(grammarAccess.getStateMachineAccess().getNameAssignment_1(), "rule__StateMachine__NameAssignment_1");
					put(grammarAccess.getStateMachineAccess().getActionclientsAssignment_3(), "rule__StateMachine__ActionclientsAssignment_3");
					put(grammarAccess.getStateMachineAccess().getServiceclientsAssignment_4(), "rule__StateMachine__ServiceclientsAssignment_4");
					put(grammarAccess.getStateMachineAccess().getActionsstatesAssignment_5(), "rule__StateMachine__ActionsstatesAssignment_5");
					put(grammarAccess.getActionClientAccess().getNameAssignment_1(), "rule__ActionClient__NameAssignment_1");
					put(grammarAccess.getActionClientAccess().getActionnameAssignment_4(), "rule__ActionClient__ActionnameAssignment_4");
					put(grammarAccess.getActionClientAccess().getActiontypeAssignment_7(), "rule__ActionClient__ActiontypeAssignment_7");
					put(grammarAccess.getServiceClientAccess().getNameAssignment_1(), "rule__ServiceClient__NameAssignment_1");
					put(grammarAccess.getServiceClientAccess().getServicenameAssignment_4(), "rule__ServiceClient__ServicenameAssignment_4");
					put(grammarAccess.getServiceClientAccess().getServicesrvAssignment_7(), "rule__ServiceClient__ServicesrvAssignment_7");
					put(grammarAccess.getActionStateAccess().getNameAssignment_1(), "rule__ActionState__NameAssignment_1");
					put(grammarAccess.getActionStateAccess().getClientnameAssignment_4(), "rule__ActionState__ClientnameAssignment_4");
					put(grammarAccess.getActionStateAccess().getTransitionsAssignment_6_0(), "rule__ActionState__TransitionsAssignment_6_0");
					put(grammarAccess.getTransitionAccess().getOutcomeAssignment_0(), "rule__Transition__OutcomeAssignment_0");
					put(grammarAccess.getTransitionAccess().getStateAssignment_2(), "rule__Transition__StateAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.best.of.robotics.ui.contentassist.antlr.internal.InternalSmachDSLParser typedParser = (org.best.of.robotics.ui.contentassist.antlr.internal.InternalSmachDSLParser) parser;
			typedParser.entryRulePrimitivePackage();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public SmachDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmachDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
