/*
* generated by Xtext
*/
package org.best.of.robotics.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SmachDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
