//ROS typedefs
#include "ros/ros.h"
#include <std_msgs/String.h>

/* protected region user include files on begin */
/* protected region user include files end */

class listener_config
{
public:

};

class listener_data
{
// autogenerated: don't touch this class
public:
//input data
    	std_msgs::String in_sub;
  
	
//output data
 

};

class listener_impl
{
	/* protected region user member variables on begin */
	/* protected region user member variables end */

public:
    listener_impl() 
    {
        /* protected region user constructor on begin */
		/* protected region user constructor end */
    }
    void configure(listener_config config) 
    {
        /* protected region user configure on begin */
		/* protected region user configure end */
    }
    void update(listener_data &data, listener_config config)
    {
        /* protected region user update on begin */
	std::cout << "Received: " << data.in_sub << "\n";
		/* protected region user update end */
    }




    
    /* protected region user additional functions on begin */
	/* protected region user additional functions end */
    
};
