/*
* generated by Xtext
*/
package org.best.of.robotics.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.best.of.robotics.services.SmachDSLGrammarAccess;

public class SmachDSLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SmachDSLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.best.of.robotics.parser.antlr.internal.InternalSmachDSLParser createParser(XtextTokenStream stream) {
		return new org.best.of.robotics.parser.antlr.internal.InternalSmachDSLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "PrimitivePackage";
	}
	
	public SmachDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmachDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
