/*
 * generated by Xtext
 */
package org.ros.model.ros_package.dsl;

import org.eclipse.xtext.parser.IParser;
import org.ros.model.ros_package.dsl.indenting.IndentingParser;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class RosPackageRuntimeModule extends
		org.ros.model.ros_package.dsl.AbstractRosPackageRuntimeModule {

	@Override
	public Class<? extends IParser> bindIParser() {
		return IndentingParser.class;
	}

}
